'use client';

import { motion } from 'framer-motion';
import { Localize } from '@deriv-com/translations';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import type { DigitStats } from '../lib/types';

interface DigitStatsBarProps {
  digitStats: DigitStats;
  selectedDigit: number;
  onDigitSelect: (digit: number) => void;
  /** The digit currently being generated by the live tick stream — when
   *  provided, a glowing pointer glides to whichever button this matches,
   *  matching the animation on the operations (robot) page. */
  lastDigit?: number | null;
}

// Same spring used for the equivalent glide animation on the operations
// (robot) page, so the motion feels identical across both pages.
const GLIDE_SPRING = { type: 'spring', stiffness: 340, damping: 30, mass: 0.7 } as const;

export function DigitStatsBar({
  digitStats,
  selectedDigit,
  onDigitSelect,
  lastDigit,
}: DigitStatsBarProps) {
  const maxPct = Math.max(...digitStats.percentages);
  const minPct = Math.min(...digitStats.percentages);

  return (
    <div className="h-full flex flex-col min-h-0">
      <span className="text-xs sm:text-sm text-muted-foreground mb-2 sm:mb-3">
        <Localize i18n_default_text="Last digit prediction" />
      </span>
      <div className="flex-1 flex items-center min-h-0">
        <div className="grid grid-cols-5 gap-1.5 sm:gap-3 place-items-center w-full">
        {digitStats.percentages.map((pct, digit) => {
          const isSelected = digit === selectedDigit;
          const isCurrent = digit === lastDigit;
          const isHighest = digitStats.totalTicks > 0 && pct === maxPct;
          const isLowest = digitStats.totalTicks > 0 && pct === minPct;

          return (
            <div key={digit} className="flex flex-col items-center gap-1 sm:gap-1.5">
              <Button
                variant={isSelected ? 'default' : 'outline'}
                onClick={() => onDigitSelect(digit)}
                className={cn(
                  'relative w-11 h-11 sm:w-14 sm:h-14 text-base sm:text-xl font-semibold rounded-lg p-0',
                  !isSelected && 'bg-muted/50 border-muted-foreground/20'
                )}
              >
                {isCurrent && (
                  <>
                    {/* Caret — glides above whichever digit is currently live */}
                    <motion.span
                      layoutId="digit-pointer-caret-live"
                      transition={GLIDE_SPRING}
                      className="pointer-events-none absolute -top-2.5 left-1/2 h-0 w-0 -translate-x-1/2 border-x-[5px] border-t-[6px] border-x-transparent border-t-primary"
                    />
                    {/* Glow ring — glides to sit around the currently live digit */}
                    <motion.span
                      layoutId="digit-pointer-glow-live"
                      transition={GLIDE_SPRING}
                      className="pointer-events-none absolute -inset-0.5 rounded-lg ring-2 ring-primary shadow-[0_0_14px_2px] shadow-primary/50"
                    />
                  </>
                )}
                {digit}
              </Button>
              <span
                className={cn(
                  'text-xs font-mono',
                  isHighest && 'text-green-500 font-semibold',
                  isLowest && 'text-red-500 font-semibold',
                  !isHighest && !isLowest && 'text-muted-foreground'
                )}
              >
                {pct.toFixed(1)}%
              </span>
            </div>
          );
        })}
        </div>
      </div>
    </div>
  );
}
