'use client';

import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { toast } from 'sonner';
import { Localize } from '@deriv-com/translations';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { SymbolSelector } from '@/components/custom/symbol-selector';
import { TradeControls } from '@/components/trade-controls';
import { PositionsTable } from '@/components/custom/positions-table';
import { cn } from '@/lib/utils';
import { useAppTranslations } from '@/components/custom/i18n-provider';
import { computeDigitStats, getLastDigit } from '@/lib/digit-stats';
import {
  useEvenOddBot,
  eoClassOf,
  type EoPhase,
  type EoStopReason,
  type EoTradingMode,
  type EoTradeType,
  type EoRunMode,
  type EoWatchParity,
  type EoWatchRange,
  type EoDetectionClass,
  type EoLogEntry,
} from '@/hooks/use-even-odd-bot';
import { MinervaVictoryDialog } from '@/components/custom/minerva-victory-dialog';
import { MinervaDefeatDialog } from '@/components/custom/minerva-defeat-dialog';
import { MinervaInsufficientFundsDialog } from '@/components/custom/minerva-insufficient-funds-dialog';
import { MinervaSettingsProfilesDialog } from '@/components/custom/minerva-settings-profiles-dialog';
import type {
  ActiveSymbol,
  Tick,
  DurationLimits,
  ProposalInfo,
  BuyResult,
  DerivWS,
} from '@deriv/core';
import type {
  ContractMode,
  TradeType,
  DigitStats,
  OpenPosition,
  ClosedPosition,
} from '@/lib/types';

const DIGIT_CONTRACT_TYPES = [
  'DIGITMATCH',
  'DIGITDIFF',
  'DIGITOVER',
  'DIGITUNDER',
  'DIGITEVEN',
  'DIGITODD',
];

type Tab = 'digits' | 'trades' | 'logs';

export interface EvenOddViewProps {
  isConnected: boolean;
  isAuthenticated: boolean;
  balanceLabel: string | null;
  balance: number | null;
  ws: DerivWS | null;

  symbols: ActiveSymbol[];
  activeSymbol: ActiveSymbol | null;
  selectSymbol: (symbol: string) => void;
  currentTick: Tick | null;
  prices: number[];
  pipSize: number;

  tradeType: TradeType;
  setTradeType: (type: TradeType) => void;
  contractMode: ContractMode;
  setContractMode: (mode: ContractMode) => void;
  selectedDigit: number;
  setSelectedDigit: (digit: number) => void;
  stake: string;
  setStake: (value: string) => void;
  duration: number;
  setDuration: (value: number) => void;
  durationLimits: DurationLimits;
  proposal: ProposalInfo | null;
  isProposalLoading: boolean;
  buyContract: () => Promise<void>;
  isBuying: boolean;
  buyResult: BuyResult | null;
  buyError: string | null;
  clearBuyResult: () => void;

  openPositions: OpenPosition[];
  closedPositions: ClosedPosition[];
  sellContract: (contractId: number, bidPrice: string) => Promise<void>;
  sellingId: number | null;
  sellError: string | null;
  clearSellError: () => void;
}

const HISTORY_WINDOW = 100;
const RECENT_DIGITS_SHOWN = 26;
const EO_SETTINGS_PROFILES_STORAGE_KEY = 'centurium:evenodd-settings-profiles';
const EO_SETTINGS_ACTIVE_PROFILE_STORAGE_KEY = 'centurium:evenodd-settings-active-profile';

interface SavedEoSettings {
  duration: number;
  streakCount: string;
  confirmationStreak: string;
  watchParity: EoWatchParity;
  watchRange: EoWatchRange;
  initialStake: string;
  stakeMultiplier: string;
  martingaleAfterLosses: string;
  armTimeLimitSeconds: string;
  tradingMode: EoTradingMode;
  botTradeType: EoTradeType;
  runMode: EoRunMode;
  takeProfit: string;
  stopLoss: string;
  runTakeProfit: string;
}

/** A named, timestamped settings snapshot — one entry per saved profile. */
interface EoSettingsProfileRecord {
  name: string;
  savedAt: number;
  settings: SavedEoSettings;
}

type EoSettingsProfilesMap = Record<string, EoSettingsProfileRecord>;

const TOGGLE_ITEM =
  'flex-1 rounded-full text-xs font-semibold text-foreground/70 data-[state=on]:bg-background data-[state=on]:text-primary data-[state=on]:font-bold data-[state=on]:shadow-sm hover:text-foreground';
const FIELD =
  'space-y-1.5 rounded-lg p-1.5 -m-1.5 transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]';

// Same spring used for the equivalent glide animation on the standalone
// Digits page, so the motion feels identical across both pages.
const ROBOT_GLIDE_SPRING = { type: 'spring', stiffness: 340, damping: 30, mass: 0.7 } as const;

function DigitFrequencyRow({
  digitStats,
  selectedDigit,
  onSelect,
  lastDigit,
}: {
  digitStats: DigitStats;
  selectedDigit: number;
  onSelect: (digit: number) => void;
  /** The digit currently being generated by the live tick stream — when
   *  provided, a glowing pointer glides to whichever button this matches,
   *  matching the animation on the standalone Digits page. */
  lastDigit?: number | null;
}) {
  const maxPct = Math.max(...digitStats.percentages);
  const minPct = Math.min(...digitStats.percentages);
  return (
    <div className="grid grid-cols-5 sm:grid-cols-10 gap-2">
      {digitStats.percentages.map((pct, digit) => {
        const isSelected = digit === selectedDigit;
        const isCurrent = digit === lastDigit;
        const isHighest = digitStats.totalTicks > 0 && pct === maxPct;
        const isLowest = digitStats.totalTicks > 0 && pct === minPct;
        return (
          <button
            key={digit}
            onClick={() => onSelect(digit)}
            className={cn(
              'relative flex flex-col items-center gap-1 rounded-md border py-2 transition-all duration-200',
              isSelected
                ? 'border-destructive ring-1 ring-destructive'
                : isHighest
                  ? 'border-emerald-500/60'
                  : 'border-border',
              'bg-muted/30 hover:bg-muted/60 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]'
            )}
          >
            {isCurrent && (
              <>
                {/* Caret — glides above whichever digit is currently live */}
                <motion.span
                  layoutId="eo-digit-pointer-caret-live"
                  transition={ROBOT_GLIDE_SPRING}
                  className="pointer-events-none absolute -top-2.5 left-1/2 h-0 w-0 -translate-x-1/2 border-x-[5px] border-t-[6px] border-x-transparent border-t-primary"
                />
                {/* Glow ring — glides to sit around the currently live digit */}
                <motion.span
                  layoutId="eo-digit-pointer-glow-live"
                  transition={ROBOT_GLIDE_SPRING}
                  className="pointer-events-none absolute -inset-0.5 rounded-md ring-2 ring-primary shadow-[0_0_14px_2px] shadow-primary/50"
                />
              </>
            )}
            <span className="text-lg font-bold text-foreground">{digit}</span>
            <span
              className={cn(
                'text-xs font-mono font-bold',
                isHighest && 'text-emerald-400',
                isLowest && 'text-rose-400',
                !isHighest && !isLowest && 'text-foreground/80'
              )}
            >
              {pct.toFixed(1)}%
            </span>
          </button>
        );
      })}
    </div>
  );
}

function DigitHistogram({ title, stats }: { title: string; stats: DigitStats }) {
  const maxPct = Math.max(...stats.percentages, 1);
  const highest = Math.max(...stats.percentages);
  const lowest = Math.min(...stats.percentages);
  return (
    <div className="flex flex-col gap-2">
      <span className="text-xs font-semibold text-foreground/90">{title}</span>
      <div className="flex items-end gap-1 h-28">
        {stats.percentages.map((pct, digit) => {
          const isHighest = stats.totalTicks > 0 && pct === highest;
          const isLowest = stats.totalTicks > 0 && pct === lowest;
          return (
            <div
              key={digit}
              className="flex-1 flex flex-col items-center gap-1 rounded-md py-1 transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]"
            >
              <span
                className={cn(
                  'text-[10px] font-bold',
                  isHighest ? 'text-emerald-400' : isLowest ? 'text-rose-400' : 'text-foreground/80'
                )}
              >
                {stats.totalTicks > 0 ? `${Math.round(pct)}%` : ''}
              </span>
              <div className="w-full h-20 flex items-end">
                <div
                  className={cn(
                    'w-full rounded-sm',
                    isHighest ? 'bg-emerald-500' : isLowest ? 'bg-rose-500/70' : 'bg-muted-foreground/50'
                  )}
                  style={{ height: `${Math.max((pct / maxPct) * 100, 3)}%` }}
                />
              </div>
              <span className="text-[10px] font-semibold text-foreground/80">{digit}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function TickSparkline({ prices }: { prices: number[] }) {
  const points = prices.slice(-24);
  if (points.length < 2) {
    return (
      <div className="h-24 flex items-center justify-center text-xs font-semibold text-foreground/90">
        <Localize i18n_default_text="Waiting for enough ticks…" />
      </div>
    );
  }
  const min = Math.min(...points);
  const max = Math.max(...points);
  const range = max - min || 1;
  const w = 600;
  const h = 90;
  const coords = points.map((p, i) => {
    const x = (i / (points.length - 1)) * w;
    const y = h - ((p - min) / range) * (h - 16) - 8;
    return [x, y] as const;
  });
  const path = coords.map(([x, y], i) => `${i === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`).join(' ');
  return (
    <svg viewBox={`0 0 ${w} ${h}`} className="w-full h-24" preserveAspectRatio="none">
      <path d={path} fill="none" stroke="currentColor" className="text-primary" strokeWidth={2} />
      {coords.map(([x, y], i) => {
        const isLast = i === coords.length - 1;
        const isUp = i > 0 && points[i] >= points[i - 1];
        return (
          <circle
            key={i}
            cx={x}
            cy={y}
            r={isLast ? 4 : 2.5}
            className={isUp ? 'fill-emerald-500' : 'fill-rose-500'}
          />
        );
      })}
    </svg>
  );
}

type EoPanelKey = 'settings' | 'analysis' | 'manual';

/**
 * Same premium hover micro-interaction used on the homepage's entry cards:
 * the hovered panel lifts/scales up and its `.panel-glow` breathing glow
 * gets a brighter overlay faded in on top (rather than swapping the
 * keyframes, which would make the glow jump instead of smoothly
 * intensifying). The other panels dim slightly while one is hovered.
 */
function useEoPanelHover() {
  const [hovered, setHovered] = useState<EoPanelKey | null>(null);

  function panelProps(key: EoPanelKey) {
    const isHovered = hovered === key;
    const isDimmed = hovered !== null && hovered !== key;
    return {
      onMouseEnter: () => setHovered(key),
      onMouseLeave: () =>
        setHovered((current: EoPanelKey | null) => (current === key ? null : current)),
      onFocus: () => setHovered(key),
      onBlur: () =>
        setHovered((current: EoPanelKey | null) => (current === key ? null : current)),
      style: {
        transform: isHovered ? 'translateY(-4px) scale(1.02)' : 'translateY(0) scale(1)',
        opacity: isDimmed ? 0.92 : 1,
      },
      className:
        'relative transition-[transform,opacity] duration-300 ease-out will-change-transform',
      overlayClassName:
        'pointer-events-none absolute inset-0 rounded-[inherit] transition-opacity duration-300 ease-out shadow-[0_14px_32px_-12px_rgba(0,0,0,0.35),0_0_0_1px_rgba(59,130,246,0.55),0_0_26px_4px_rgba(59,130,246,0.45),0_0_56px_14px_rgba(59,130,246,0.22)]' +
        (isHovered ? ' opacity-100' : ' opacity-0'),
    };
  }

  return panelProps;
}

function eoClassLabel(cls: EoDetectionClass, localize: (t: string) => string): string {
  switch (cls) {
    case 'odd-over':
      return `${localize('Odd')} · ${localize('Over 4')}`;
    case 'even-over':
      return `${localize('Even')} · ${localize('Over 4')}`;
    case 'odd-under':
      return `${localize('Odd')} · ${localize('Under 5')}`;
    case 'even-under':
      return `${localize('Even')} · ${localize('Under 5')}`;
    default:
      return '';
  }
}

function getStatusLabel(
  phase: EoPhase,
  armedClass: EoDetectionClass,
  confirmProgress: number,
  confirmationStreak: string,
  runProgress: { cls: EoDetectionClass; count: number },
  streakCount: string,
  burstActive: boolean,
  burstPnl: number,
  localize: (t: string) => string
): string {
  const pnlText = burstActive ? ` (${burstPnl >= 0 ? '+' : ''}${burstPnl.toFixed(2)})` : '';
  switch (phase) {
    case 'awaiting-proposal':
    case 'awaiting-buy':
      return `${localize('Placing trade…')}${pnlText}`;
    case 'awaiting-settlement':
      return `${localize('Trade running…')}${pnlText}`;
    default:
      if (armedClass) {
        return `${eoClassLabel(armedClass, localize)} ${localize('ARMED')} — ${localize(
          'waiting for confirmation streak'
        )} (${confirmProgress}/${confirmationStreak})`;
      }
      if (runProgress.cls && runProgress.count > 0) {
        return `${localize('Watching…')} ${eoClassLabel(runProgress.cls, localize)} ${runProgress.count}/${streakCount}`;
      }
      return localize('Watching…');
  }
}

function getStoppedLabel(reason: EoStopReason, localize: (t: string) => string): string | null {
  switch (reason) {
    case 'manual':
      return localize('Stopped: Manual');
    case 'take-profit':
      return localize('Stopped: Take Profit');
    case 'stop-loss':
      return localize('Stopped: Stop Loss');
    case 'insufficient-funds':
      return localize('Stopped: Insufficient Funds');
    case 'timeout-proposal':
      return localize('Stopped: No price received — check Reports');
    case 'timeout-buy':
      return localize('Stopped: Buy not confirmed — check Reports');
    case 'timeout-settlement':
      return localize('Stopped: No trade result — check Reports');
    default:
      return null;
  }
}

/** Odd digits green, even digits red; stronger shade = Over 4 (5-9), lighter
 *  = Under 5 (0-4). Digits outside the watched classes are muted. */
function EoDigitRecord({
  digits,
  watchParity,
  watchRange,
}: {
  digits: number[];
  watchParity: EoWatchParity;
  watchRange: EoWatchRange;
}) {
  if (digits.length === 0) return null;
  return (
    <div className="flex flex-wrap gap-1 rounded-md bg-muted/30 p-2">
      {digits.map((d, i) => {
        const isNewest = i === digits.length - 1;
        const cls = eoClassOf(d, watchParity, watchRange);
        const colorClass =
          cls === 'odd-over'
            ? 'bg-emerald-500/45 text-emerald-300'
            : cls === 'odd-under'
              ? 'bg-emerald-500/15 text-emerald-400'
              : cls === 'even-over'
                ? 'bg-rose-500/45 text-rose-300'
                : cls === 'even-under'
                  ? 'bg-rose-500/15 text-rose-400'
                  : 'bg-muted text-muted-foreground/70';
        return (
          <span
            key={i}
            className={cn(
              'flex h-5 w-5 items-center justify-center rounded text-[10px] font-bold tabular-nums',
              colorClass,
              isNewest && 'ring-2 ring-primary'
            )}
          >
            {d}
          </span>
        );
      })}
    </div>
  );
}

export function EvenOddView({
  isConnected,
  isAuthenticated,
  balanceLabel,
  balance,
  symbols,
  activeSymbol,
  selectSymbol,
  currentTick,
  prices,
  pipSize,
  tradeType,
  setTradeType,
  contractMode,
  setContractMode,
  selectedDigit,
  setSelectedDigit,
  stake,
  setStake,
  duration,
  setDuration,
  durationLimits,
  proposal,
  isProposalLoading,
  buyContract,
  isBuying,
  buyResult,
  buyError,
  clearBuyResult,
  openPositions,
  closedPositions,
  sellContract,
  sellingId,
  sellError,
  clearSellError,
}: EvenOddViewProps) {
  const { localize } = useAppTranslations();
  const [activeTab, setActiveTab] = useState<Tab>('digits');
  const panelHover = useEoPanelHover();
  const settingsPanel = panelHover('settings');
  const analysisPanel = panelHover('analysis');
  const manualPanel = panelHover('manual');

  const [streakCount, setStreakCount] = useState('4');
  const [confirmationStreak, setConfirmationStreak] = useState('0');
  const [watchParity, setWatchParity] = useState<EoWatchParity>('both');
  const [watchRange, setWatchRange] = useState<EoWatchRange>('both');
  const [initialStake, setInitialStake] = useState('1');
  const [stakeMultiplier, setStakeMultiplier] = useState('2.2');
  const [martingaleAfterLosses, setMartingaleAfterLosses] = useState('0');
  const [armTimeLimitSeconds, setArmTimeLimitSeconds] = useState('0');
  const [tradingMode, setTradingMode] = useState<EoTradingMode>('neutral');
  const [botTradeType, setBotTradeType] = useState<EoTradeType>('eo');
  const [runMode, setRunMode] = useState<EoRunMode>('burst');
  const [takeProfit, setTakeProfit] = useState('0');
  const [stopLoss, setStopLoss] = useState('0');
  const [runTakeProfit, setRunTakeProfit] = useState('0');

  const [eoProfiles, setEoProfiles] = useState<EoSettingsProfilesMap>({});
  const [activeProfileName, setActiveProfileName] = useState<string | null>(null);
  const [profilesDialogOpen, setProfilesDialogOpen] = useState(false);

  const applySettings = (saved: Partial<SavedEoSettings>) => {
    if (typeof saved.duration === 'number') setDuration(saved.duration);
    if (typeof saved.streakCount === 'string') setStreakCount(saved.streakCount);
    if (typeof saved.confirmationStreak === 'string') setConfirmationStreak(saved.confirmationStreak);
    if (typeof saved.watchParity === 'string') setWatchParity(saved.watchParity);
    if (typeof saved.watchRange === 'string') setWatchRange(saved.watchRange);
    if (typeof saved.initialStake === 'string') setInitialStake(saved.initialStake);
    if (typeof saved.stakeMultiplier === 'string') setStakeMultiplier(saved.stakeMultiplier);
    if (typeof saved.martingaleAfterLosses === 'string') setMartingaleAfterLosses(saved.martingaleAfterLosses);
    if (typeof saved.armTimeLimitSeconds === 'string') setArmTimeLimitSeconds(saved.armTimeLimitSeconds);
    if (typeof saved.tradingMode === 'string') setTradingMode(saved.tradingMode);
    if (typeof saved.botTradeType === 'string') setBotTradeType(saved.botTradeType);
    if (typeof saved.runMode === 'string') setRunMode(saved.runMode);
    if (typeof saved.takeProfit === 'string') setTakeProfit(saved.takeProfit);
    if (typeof saved.stopLoss === 'string') setStopLoss(saved.stopLoss);
    if (typeof saved.runTakeProfit === 'string') setRunTakeProfit(saved.runTakeProfit);
  };

  const currentSettingsSnapshot = (): SavedEoSettings => ({
    duration,
    streakCount,
    confirmationStreak,
    watchParity,
    watchRange,
    initialStake,
    stakeMultiplier,
    martingaleAfterLosses,
    armTimeLimitSeconds,
    tradingMode,
    botTradeType,
    runMode,
    takeProfit,
    stopLoss,
    runTakeProfit,
  });

  const persistProfiles = (next: EoSettingsProfilesMap) => {
    window.localStorage.setItem(EO_SETTINGS_PROFILES_STORAGE_KEY, JSON.stringify(next));
  };

  // Load any saved profiles once on mount, and re-apply the last one used.
  useEffect(() => {
    try {
      const raw = window.localStorage.getItem(EO_SETTINGS_PROFILES_STORAGE_KEY);
      const map: EoSettingsProfilesMap = raw ? (JSON.parse(raw) as EoSettingsProfilesMap) : {};
      setEoProfiles(map);

      const lastActive = window.localStorage.getItem(EO_SETTINGS_ACTIVE_PROFILE_STORAGE_KEY);
      if (lastActive && map[lastActive]) {
        applySettings(map[lastActive].settings);
        setActiveProfileName(lastActive);
      }
    } catch {
      // Ignore malformed/unavailable storage — fields just keep their defaults.
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleSaveProfile = (name: string) => {
    try {
      const next: EoSettingsProfilesMap = {
        ...eoProfiles,
        [name]: { name, savedAt: Date.now(), settings: currentSettingsSnapshot() },
      };
      persistProfiles(next);
      setEoProfiles(next);
      setActiveProfileName(name);
      window.localStorage.setItem(EO_SETTINGS_ACTIVE_PROFILE_STORAGE_KEY, name);
      toast.success(localize('Saved profile "{{name}}"', { name }));
    } catch {
      toast.error(localize('Could not save settings on this device.'));
    }
  };

  const handleLoadProfile = (name: string) => {
    const profile = eoProfiles[name];
    if (!profile) return;
    applySettings(profile.settings);
    setActiveProfileName(name);
    try {
      window.localStorage.setItem(EO_SETTINGS_ACTIVE_PROFILE_STORAGE_KEY, name);
    } catch {
      // Non-fatal — the settings are already applied in-memory either way.
    }
    toast.success(localize('Loaded profile "{{name}}"', { name }));
    setProfilesDialogOpen(false);
  };

  const handleDeleteProfile = (name: string) => {
    const next = { ...eoProfiles };
    delete next[name];
    try {
      persistProfiles(next);
    } catch {
      // Ignore — in-memory state below still reflects the deletion this session.
    }
    setEoProfiles(next);
    if (activeProfileName === name) {
      setActiveProfileName(null);
      try {
        window.localStorage.removeItem(EO_SETTINGS_ACTIVE_PROFILE_STORAGE_KEY);
      } catch {
        // Non-fatal.
      }
    }
    toast.success(localize('Deleted profile "{{name}}"', { name }));
  };

  const priceHistory = useMemo(() => prices.slice(-HISTORY_WINDOW), [prices]);
  const stats = useMemo(() => computeDigitStats(priceHistory, pipSize), [priceHistory, pipSize]);
  const last25 = useMemo(
    () => computeDigitStats(priceHistory.slice(-25), pipSize),
    [priceHistory, pipSize]
  );
  const last50 = useMemo(
    () => computeDigitStats(priceHistory.slice(-50), pipSize),
    [priceHistory, pipSize]
  );
  const last100 = useMemo(
    () => computeDigitStats(priceHistory.slice(-100), pipSize),
    [priceHistory, pipSize]
  );
  const recentDigits = useMemo(
    () => priceHistory.slice(-RECENT_DIGITS_SHOWN).map((p) => getLastDigit(p, pipSize)),
    [priceHistory, pipSize]
  );
  const lastDigit = useMemo(
    () => (currentTick ? getLastDigit(currentTick.quote, pipSize) : null),
    [currentTick, pipSize]
  );

  const bot = useEvenOddBot({
    currentTick,
    pipSize,
    setStake,
    setContractMode,
    setSelectedDigit,
    proposal,
    isProposalLoading,
    buyContract,
    buyResult,
    buyError,
    clearBuyResult,
    openPositions,
    balance,
  });
  const botRunning = bot.running;

  const [victoryOpen, setVictoryOpen] = useState(false);
  useEffect(() => {
    if (bot.stoppedReason === 'take-profit') setVictoryOpen(true);
  }, [bot.stoppedReason]);
  const [defeatOpen, setDefeatOpen] = useState(false);
  useEffect(() => {
    if (bot.stoppedReason === 'stop-loss') setDefeatOpen(true);
  }, [bot.stoppedReason]);
  const [insufficientOpen, setInsufficientOpen] = useState(false);
  useEffect(() => {
    if (bot.stoppedReason === 'insufficient-funds') setInsufficientOpen(true);
  }, [bot.stoppedReason]);

  useEffect(() => {
    const where: Record<string, string> = {
      'timeout-proposal': 'waiting for a price quote',
      'timeout-buy': 'waiting for the buy confirmation',
      'timeout-settlement': 'waiting for the contract to settle',
    };
    const reason = bot.stoppedReason;
    if (reason && where[reason]) {
      toast.error(localize('Even/Odd stopped: no response'), {
        description: `Stuck ${where[reason]}. Check Reports for any open contract before restarting.`,
        duration: 15000,
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [bot.stoppedReason]);

  const handleStart = () => {
    if (bot.running) {
      bot.stop('manual');
      toast.info(localize('Robot stopped'));
      return;
    }
    const streak = parseInt(streakCount, 10);
    const confirm = parseInt(confirmationStreak, 10);
    if (!streak || streak < 2 || streak > 20) {
      toast.error(localize('Enter a valid Streak Count (2-20) first.'));
      return;
    }
    if (Number.isNaN(confirm) || confirm < 0 || confirm > 9) {
      toast.error(localize('Enter a valid Confirmation Streak (0-9) first.'));
      return;
    }
    const baseStake = parseFloat(initialStake);
    if (!baseStake || baseStake <= 0) {
      toast.error(localize('Enter a valid stake first.'));
      return;
    }
    bot.start({
      streakCount: streak,
      confirmationStreak: confirm,
      watchParity,
      watchRange,
      initialStake: baseStake,
      stakeMultiplier: parseFloat(stakeMultiplier) || 1,
      martingaleStartAfter: Math.max(0, parseInt(martingaleAfterLosses, 10) || 0),
      armTimeLimitSeconds: Math.max(0, parseInt(armTimeLimitSeconds, 10) || 0),
      tradingMode,
      tradeType: botTradeType,
      runMode,
      takeProfit: parseFloat(takeProfit) || 0,
      stopLoss: parseFloat(stopLoss) || 0,
      runTakeProfit: parseFloat(runTakeProfit) || 0,
    });
    toast.info(localize('Robot started'), {
      description:
        tradingMode === 'neutral'
          ? localize('Watching for digit runs — pick Trend or Counter to actually trade.')
          : localize('Watching for digit runs on the digit stream.'),
    });
  };

  const contractLabels: Record<string, string> = {
    DIGITMATCH: localize('Digit Match'),
    DIGITDIFF: localize('Digit Differs'),
    DIGITOVER: localize('Digit Over'),
    DIGITUNDER: localize('Digit Under'),
    DIGITEVEN: localize('Digit Even'),
    DIGITODD: localize('Digit Odd'),
  };
  const tradeTypeOptions: { value: TradeType; label: string }[] = [
    { value: 'matches-differs', label: localize('Matches/Differs') },
    { value: 'over-under', label: localize('Over/Under') },
    { value: 'even-odd', label: localize('Even/Odd') },
  ];
  const stoppedLabel = getStoppedLabel(bot.stoppedReason, localize);

  return (
    <>
      <MinervaVictoryDialog
        open={victoryOpen}
        onOpenChange={setVictoryOpen}
        onContinue={() => setVictoryOpen(false)}
        durationMs={bot.sessionDurationMs}
      />
      <MinervaDefeatDialog
        open={defeatOpen}
        onOpenChange={setDefeatOpen}
        onContinue={() => setDefeatOpen(false)}
        durationMs={bot.sessionDurationMs}
      />
      <MinervaInsufficientFundsDialog
        open={insufficientOpen}
        onOpenChange={setInsufficientOpen}
        onContinue={() => setInsufficientOpen(false)}
        durationMs={bot.sessionDurationMs}
      />
      <MinervaSettingsProfilesDialog
        open={profilesDialogOpen}
        onOpenChange={setProfilesDialogOpen}
        profiles={eoProfiles}
        activeProfileName={activeProfileName}
        onSave={handleSaveProfile}
        onLoad={handleLoadProfile}
        onDelete={handleDeleteProfile}
      />

      <div className="w-full max-w-[1760px] mx-auto px-3 py-4 sm:px-4 flex flex-col lg:flex-row gap-4">
        {/* Left: bot settings */}
        <Card
          className={`panel-glow bg-card/60 backdrop-blur-md flex flex-col w-full lg:w-[420px] lg:shrink-0 lg:sticky lg:top-[88px] lg:max-h-[calc(100dvh-124px)] self-start overflow-visible ${settingsPanel.className}`}
          style={settingsPanel.style}
          onMouseEnter={settingsPanel.onMouseEnter}
          onMouseLeave={settingsPanel.onMouseLeave}
          onFocus={settingsPanel.onFocus}
          onBlur={settingsPanel.onBlur}
        >
          <div aria-hidden className={settingsPanel.overlayClassName} />
          <CardHeader className="pb-3 shrink-0">
            <CardTitle className="text-xl font-bold tracking-wide">EVEN / ODD</CardTitle>
            <p className="text-xs font-semibold text-foreground/90">
              {isConnected ? (
                balanceLabel ? (
                  balanceLabel
                ) : (
                  <Localize i18n_default_text="Connected" />
                )
              ) : (
                <Localize i18n_default_text="Not connected" />
              )}
            </p>
            <div className="flex items-center justify-between rounded-md bg-muted/40 px-2.5 py-1.5 mt-1">
              <span
                className={cn(
                  'text-xs font-bold pr-2 min-w-0',
                  botRunning ? 'text-emerald-400' : 'text-foreground/85'
                )}
              >
                {getStatusLabel(
                  bot.phase,
                  bot.armedClass,
                  bot.confirmProgress,
                  confirmationStreak,
                  bot.runProgress,
                  streakCount,
                  bot.burstActive,
                  bot.burstPnl,
                  localize
                )}
              </span>
              <span
                className={cn(
                  'text-sm font-mono font-bold tabular-nums',
                  bot.pnl >= 0 ? 'text-emerald-400' : 'text-rose-400'
                )}
              >
                {bot.pnl >= 0 ? '+' : ''}
                {bot.pnl.toFixed(2)}
              </span>
            </div>
            {!bot.running && stoppedLabel && (
              <p className="text-[11px] text-muted-foreground px-0.5">{stoppedLabel}</p>
            )}
            {bot.running && !bot.burstActive && bot.lastBurstOutcome === 'won' && (
              <p className="text-[11px] text-muted-foreground px-0.5">
                <Localize i18n_default_text="Last run finished in profit — watching for the next signal." />
              </p>
            )}
            {bot.running && !bot.burstActive && bot.lastBurstOutcome === 'error' && (
              <p className="text-[11px] text-muted-foreground px-0.5">
                <Localize i18n_default_text="Last trade failed — watching for the next signal." />
              </p>
            )}
          </CardHeader>
          <CardContent className="space-y-3 lg:flex-1 lg:min-h-0 lg:overflow-y-auto">
            <fieldset disabled={botRunning} className="space-y-3 border-0 p-0 m-0 min-w-0">
              <div className={FIELD}>
                <Label className="text-xs font-semibold text-foreground/90">
                  <Localize i18n_default_text="Market" />
                </Label>
                <SymbolSelector
                  symbols={symbols}
                  activeSymbol={activeSymbol}
                  onSymbolChange={selectSymbol}
                />
              </div>

              <div className={FIELD}>
                <Label className="text-xs font-semibold text-foreground/90">
                  <Localize i18n_default_text="Duration" />
                </Label>
                <Input
                  type="number"
                  value={duration}
                  onChange={(e) => {
                    const val = parseInt(e.target.value, 10);
                    if (!isNaN(val)) setDuration(val);
                  }}
                  min={durationLimits.min}
                  max={durationLimits.max}
                  labelRight={localize('Ticks')}
                />
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div className={FIELD}>
                  <Label className="text-xs font-semibold text-foreground/90">
                    <Localize i18n_default_text="Stake" />
                  </Label>
                  <Input value={initialStake} onChange={(e) => setInitialStake(e.target.value)} />
                </div>
                <div className={FIELD}>
                  <Label className="text-xs font-semibold text-foreground/90">
                    <Localize i18n_default_text="Stake Multiplier" />
                  </Label>
                  <Input value={stakeMultiplier} onChange={(e) => setStakeMultiplier(e.target.value)} />
                </div>
              </div>

              <div className={FIELD}>
                <Label
                  className="text-xs font-semibold text-foreground/90"
                  title={localize(
                    'Stays at the initial stake for this many losses before the multiplier kicks in. 0 = multiply from the first loss.'
                  )}
                >
                  <Localize i18n_default_text="Start Martingale after N losses" />
                </Label>
                <Input
                  value={martingaleAfterLosses}
                  onChange={(e) => setMartingaleAfterLosses(e.target.value)}
                />
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div className={FIELD}>
                  <Label
                    className="text-xs font-semibold text-foreground/90"
                    title={localize(
                      'N consecutive digits in the same class (e.g. all odd AND all over 4) required to arm a run. With 4: 7-9-5-7 arms Odd/Over, 3-3-1-3 arms Odd/Under, 2-2-4-0 arms Even/Under.'
                    )}
                  >
                    <Localize i18n_default_text="Streak Count" />
                  </Label>
                  <Input
                    type="number"
                    min={2}
                    max={20}
                    value={streakCount}
                    onChange={(e) => setStreakCount(e.target.value)}
                  />
                </div>
                <div className={FIELD}>
                  <Label
                    className="text-xs font-semibold text-foreground/90"
                    title={localize(
                      'M more consecutive digits of the same class, uninterrupted, required after arming before the trade fires. 0 = fire immediately once the run is complete.'
                    )}
                  >
                    <Localize i18n_default_text="Confirmation Streak" />
                  </Label>
                  <Input
                    type="number"
                    min={0}
                    max={9}
                    value={confirmationStreak}
                    onChange={(e) => setConfirmationStreak(e.target.value)}
                  />
                </div>
              </div>

              <div className={FIELD}>
                <Label
                  className="text-xs font-semibold text-foreground/90"
                  title={localize(
                    'Seconds a run may stay ARMED without reaching the confirmation streak before the arm is abandoned and the bot goes back to watching for a fresh run. 0 = no time limit.'
                  )}
                >
                  <Localize i18n_default_text="ARM Time Limit (seconds)" />
                </Label>
                <Input
                  type="number"
                  min={0}
                  max={3600}
                  value={armTimeLimitSeconds}
                  onChange={(e) => setArmTimeLimitSeconds(e.target.value)}
                />
              </div>

              <div className={FIELD}>
                <Label className="text-xs font-semibold text-foreground/90">
                  <Localize i18n_default_text="Watch: Even / Odd" />
                </Label>
                <ToggleGroup
                  type="single"
                  value={watchParity}
                  onValueChange={(v) => {
                    if (v) setWatchParity(v as EoWatchParity);
                  }}
                  className="w-full gap-0 rounded-full bg-muted p-1"
                >
                  <ToggleGroupItem value="both" className={TOGGLE_ITEM}>
                    <Localize i18n_default_text="Both" />
                  </ToggleGroupItem>
                  <ToggleGroupItem value="odd" className={TOGGLE_ITEM}>
                    <Localize i18n_default_text="Odd" />
                  </ToggleGroupItem>
                  <ToggleGroupItem value="even" className={TOGGLE_ITEM}>
                    <Localize i18n_default_text="Even" />
                  </ToggleGroupItem>
                </ToggleGroup>
              </div>

              <div className={FIELD}>
                <Label className="text-xs font-semibold text-foreground/90">
                  <Localize i18n_default_text="Watch: Over / Under" />
                </Label>
                <ToggleGroup
                  type="single"
                  value={watchRange}
                  onValueChange={(v) => {
                    if (v) setWatchRange(v as EoWatchRange);
                  }}
                  className="w-full gap-0 rounded-full bg-muted p-1"
                >
                  <ToggleGroupItem value="both" className={TOGGLE_ITEM}>
                    <Localize i18n_default_text="Both" />
                  </ToggleGroupItem>
                  <ToggleGroupItem value="over" className={TOGGLE_ITEM}>
                    <Localize i18n_default_text="Over 4" />
                  </ToggleGroupItem>
                  <ToggleGroupItem value="under" className={TOGGLE_ITEM}>
                    <Localize i18n_default_text="Under 5" />
                  </ToggleGroupItem>
                </ToggleGroup>
                <p className="text-[11px] text-muted-foreground">
                  <Localize i18n_default_text="A run is N digits in a row that are all the same class: Odd/Over (5 7 9), Even/Over (6 8), Odd/Under (1 3) or Even/Under (0 2 4). Any other digit breaks it." />
                </p>
              </div>

              <div className={FIELD}>
                <Label className="text-xs font-semibold text-foreground/90">
                  <Localize i18n_default_text="Trading Mode" />
                </Label>
                <ToggleGroup
                  type="single"
                  value={tradingMode}
                  onValueChange={(v) => {
                    if (v) setTradingMode(v as EoTradingMode);
                  }}
                  className="w-full gap-0 rounded-full bg-muted p-1"
                >
                  <ToggleGroupItem value="trend" className={TOGGLE_ITEM}>
                    <Localize i18n_default_text="Trend" />
                  </ToggleGroupItem>
                  <ToggleGroupItem value="neutral" className={TOGGLE_ITEM}>
                    <Localize i18n_default_text="Neutral" />
                  </ToggleGroupItem>
                  <ToggleGroupItem value="counter" className={TOGGLE_ITEM}>
                    <Localize i18n_default_text="Counter" />
                  </ToggleGroupItem>
                </ToggleGroup>
                <p className="text-[11px] text-muted-foreground">
                  {tradingMode === 'neutral' && (
                    <Localize i18n_default_text="Won't trade until you pick Trend or Counter." />
                  )}
                  {tradingMode === 'trend' && (
                    <Localize i18n_default_text="Trades with the run: an Odd run trades Odd, an Even run trades Even." />
                  )}
                  {tradingMode === 'counter' && (
                    <Localize i18n_default_text="Trades against the run: an Odd run trades Even, an Even run trades Odd." />
                  )}
                </p>
              </div>

              <div className={FIELD}>
                <Label className="text-xs font-semibold text-foreground/90">
                  <Localize i18n_default_text="Trade" />
                </Label>
                <ToggleGroup
                  type="single"
                  value={botTradeType}
                  onValueChange={(v) => {
                    if (v) setBotTradeType(v as EoTradeType);
                  }}
                  className="w-full gap-0 rounded-full bg-muted p-1"
                >
                  <ToggleGroupItem value="eo" className={TOGGLE_ITEM}>
                    <Localize i18n_default_text="E/O" />
                  </ToggleGroupItem>
                  <ToggleGroupItem value="uo" className={TOGGLE_ITEM}>
                    <Localize i18n_default_text="U5/O4" />
                  </ToggleGroupItem>
                  <ToggleGroupItem value="alt" className={TOGGLE_ITEM}>
                    <Localize i18n_default_text="ALT" />
                  </ToggleGroupItem>
                </ToggleGroup>
                <p className="text-[11px] text-muted-foreground">
                  {botTradeType === 'eo' && (
                    <Localize i18n_default_text="Trades Even/Odd based on the run's parity." />
                  )}
                  {botTradeType === 'uo' && (
                    <Localize i18n_default_text="Trades Over 4/Under 5 based on the run's range." />
                  )}
                  {botTradeType === 'alt' && (
                    <Localize i18n_default_text="Alternates every trade: Even/Odd, then Over 4/Under 5, then Even/Odd…" />
                  )}
                </p>
              </div>

              <div className={FIELD}>
                <Label className="text-xs font-semibold text-foreground/90">
                  <Localize i18n_default_text="Run Mode" />
                </Label>
                <ToggleGroup
                  type="single"
                  value={runMode}
                  onValueChange={(v) => {
                    if (v) setRunMode(v as EoRunMode);
                  }}
                  className="w-full gap-0 rounded-full bg-muted p-1"
                >
                  <ToggleGroupItem value="burst" className={TOGGLE_ITEM}>
                    <Localize i18n_default_text="Burst" />
                  </ToggleGroupItem>
                  <ToggleGroupItem value="continuous" className={TOGGLE_ITEM}>
                    <Localize i18n_default_text="Continuous" />
                  </ToggleGroupItem>
                </ToggleGroup>
                <p className="text-[11px] text-muted-foreground">
                  {runMode === 'burst' ? (
                    <Localize i18n_default_text="A win ends the run — the bot waits for the next signal." />
                  ) : (
                    <Localize i18n_default_text="A win keeps going — the bot re-fires immediately, straight to Take Profit/Stop Loss." />
                  )}
                </p>
              </div>

              <div className="border-t border-border pt-2 grid grid-cols-2 gap-2">
                <div className={FIELD}>
                  <Label
                    className="text-xs font-semibold text-foreground/90"
                    title={localize('Once total profit across the whole run reaches this amount, the bot stops. 0 = off.')}
                  >
                    <Localize i18n_default_text="Take Profit" />
                  </Label>
                  <Input value={takeProfit} onChange={(e) => setTakeProfit(e.target.value)} labelRight="USD" />
                </div>
                <div className={FIELD}>
                  <Label
                    className="text-xs font-semibold text-foreground/90"
                    title={localize('Once total loss across the whole run reaches this amount, the bot stops. 0 = off.')}
                  >
                    <Localize i18n_default_text="Stop Loss" />
                  </Label>
                  <Input value={stopLoss} onChange={(e) => setStopLoss(e.target.value)} labelRight="USD" />
                </div>
                <div className={cn('col-span-2', FIELD)}>
                  <Label
                    className="text-xs font-semibold text-foreground/90"
                    title={localize(
                      "Once THIS signal's own profit reaches this amount, the bot stops that signal and waits for the next one — it keeps running and never pops the Take Profit popup. 0 = off."
                    )}
                  >
                    <Localize i18n_default_text="Run TP" />
                  </Label>
                  <Input
                    value={runTakeProfit}
                    onChange={(e) => setRunTakeProfit(e.target.value)}
                    labelRight="USD"
                  />
                </div>
              </div>

              {(bot.running || bot.digitRecord.length > 0) && (
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between">
                    <Label className="text-xs font-semibold text-foreground/90">
                      <Localize i18n_default_text="Digit Record" />
                    </Label>
                    {bot.armedClass && (
                      <span className="text-[11px] font-semibold text-foreground/80">
                        {eoClassLabel(bot.armedClass, localize)} {localize('ARMED')} · {bot.confirmProgress}/
                        {confirmationStreak}
                      </span>
                    )}
                  </div>
                  <EoDigitRecord
                    digits={bot.digitRecord}
                    watchParity={watchParity}
                    watchRange={watchRange}
                  />
                </div>
              )}
            </fieldset>

            <Button
              className="w-full"
              variant="outline"
              onClick={() => setProfilesDialogOpen(true)}
            >
              <Localize i18n_default_text="Settings profiles" />
              {activeProfileName ? ` — ${activeProfileName}` : ''}
            </Button>

            <Button
              className="w-full"
              size="lg"
              variant={botRunning ? 'destructive' : 'default'}
              onClick={handleStart}
              disabled={!isConnected || !isAuthenticated}
            >
              {botRunning ? <Localize i18n_default_text="Stop" /> : <Localize i18n_default_text="Start" />}
            </Button>
            <p className="text-[11px] text-muted-foreground text-center">
              {isAuthenticated ? (
                <Localize i18n_default_text="Uses the same trading connection as Manual mode — only one can trade at a time." />
              ) : (
                <Localize i18n_default_text="Log in to run the robot." />
              )}
            </p>
          </CardContent>
        </Card>

        {/* Right: digits / trades / logs, then manual mode */}
        <div className="flex-1 min-w-0 flex flex-col gap-4">
          <Card
            className={`panel-glow bg-card/60 backdrop-blur-md h-fit ${analysisPanel.className}`}
            style={analysisPanel.style}
            onMouseEnter={analysisPanel.onMouseEnter}
            onMouseLeave={analysisPanel.onMouseLeave}
            onFocus={analysisPanel.onFocus}
            onBlur={analysisPanel.onBlur}
          >
            <div aria-hidden className={analysisPanel.overlayClassName} />
            <CardHeader className="pb-0">
              <div className="flex items-center gap-5 border-b border-border">
                {(
                  [
                    ['digits', localize('Digits')],
                    ['trades', localize('Trades')],
                    ['logs', localize('Logs')],
                  ] as [Tab, string][]
                ).map(([key, label]) => (
                  <button
                    key={key}
                    onClick={() => setActiveTab(key)}
                    className={cn(
                      'relative pb-2.5 text-sm font-bold border-b-2 -mb-px transition-colors',
                      activeTab === key
                        ? 'border-primary text-foreground'
                        : 'border-transparent text-foreground/70 hover:text-foreground'
                    )}
                  >
                    {label}
                  </button>
                ))}
              </div>
            </CardHeader>
            <CardContent className="pt-4 space-y-6">
              {activeTab === 'digits' && (
                <>
                  <div className="space-y-2">
                    <p className="text-center text-sm font-medium">
                      <Localize i18n_default_text="Digits frequency percentage" />
                    </p>
                    <DigitFrequencyRow
                      digitStats={stats}
                      selectedDigit={selectedDigit}
                      onSelect={setSelectedDigit}
                      lastDigit={lastDigit}
                    />
                  </div>

                  <div className="space-y-2">
                    <p className="text-sm font-medium">
                      <Localize i18n_default_text="Most recent digits" />
                    </p>
                    <div className="flex flex-wrap gap-1.5">
                      {recentDigits.length === 0 && (
                        <span className="text-xs font-semibold text-foreground/90">
                          <Localize i18n_default_text="Waiting for ticks…" />
                        </span>
                      )}
                      {recentDigits.map((d, i) => (
                        <span
                          key={i}
                          className={cn(
                            'w-7 h-7 flex items-center justify-center rounded-md text-sm font-bold transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]',
                            i === recentDigits.length - 1
                              ? 'bg-primary text-primary-foreground'
                              : 'bg-muted text-foreground/85'
                          )}
                        >
                          {d}
                        </span>
                      ))}
                    </div>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <DigitHistogram title={localize('Last 25 digits')} stats={last25} />
                    <DigitHistogram title={localize('Last 50 digits')} stats={last50} />
                    <DigitHistogram title={localize('Last 100 digits')} stats={last100} />
                  </div>

                  <div className="space-y-2">
                    <p className="text-sm font-medium">
                      <Localize i18n_default_text="Recent ticks" />
                    </p>
                    <TickSparkline prices={priceHistory} />
                  </div>
                </>
              )}

              {activeTab === 'trades' && (
                <>
                  {isAuthenticated ? (
                    <PositionsTable
                      openPositions={openPositions.filter((p) => DIGIT_CONTRACT_TYPES.includes(p.contract_type))}
                      closedPositions={closedPositions.filter((p) => DIGIT_CONTRACT_TYPES.includes(p.contract_type))}
                      onSell={sellContract}
                      sellingId={sellingId}
                      sellError={sellError}
                      onClearSellError={clearSellError}
                      contractTypeLabels={contractLabels}
                      className="mt-0"
                    />
                  ) : (
                    <div className="py-10 text-center text-sm text-muted-foreground">
                      <Localize i18n_default_text="Log in to see your open and closed positions." />
                    </div>
                  )}
                </>
              )}

              {activeTab === 'logs' && (
                <div className="space-y-1.5 max-h-[420px] overflow-y-auto">
                  {bot.log.length === 0 && (
                    <div className="py-10 text-center text-sm text-muted-foreground">
                      <Localize i18n_default_text="No robot activity yet — start it from the left panel." />
                    </div>
                  )}
                  {[...bot.log].reverse().map((entry: EoLogEntry) => (
                    <div
                      key={entry.id}
                      className="flex items-center justify-between text-xs rounded-md border border-border px-3 py-2"
                    >
                      <div className="flex items-center gap-2 flex-wrap">
                        {entry.signalClass && (
                          <span className="px-1.5 py-0.5 rounded text-[10px] font-semibold uppercase bg-muted text-foreground/80">
                            {eoClassLabel(entry.signalClass, localize)} {localize('run')}
                          </span>
                        )}
                        {entry.barrier && (
                          <span className="px-1.5 py-0.5 rounded text-[10px] font-semibold uppercase bg-primary/15 text-primary">
                            {localize('Traded')} {entry.barrier}
                          </span>
                        )}
                        <span className="text-foreground/80 font-medium">
                          {new Date(entry.time).toLocaleTimeString()}
                        </span>
                        {entry.exitSpot !== null && (
                          <span className="tabular-nums font-mono font-semibold text-foreground">
                            {entry.exitSpot.toFixed(pipSize)}
                          </span>
                        )}
                      </div>
                      <div className="flex items-center gap-3">
                        <span className="tabular-nums text-foreground/70">
                          {localize('Stake')} {entry.stake.toFixed(2)}
                        </span>
                        <span className={entry.won ? 'text-emerald-400 font-bold' : 'text-rose-400 font-bold'}>
                          {entry.won ? localize('Win') : localize('Loss')}
                        </span>
                        <span
                          className={cn(
                            'tabular-nums font-bold',
                            entry.profit >= 0 ? 'text-emerald-400' : 'text-rose-400'
                          )}
                        >
                          {entry.profit >= 0 ? '+' : ''}
                          {entry.profit.toFixed(2)}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>

          <Card
            className={`panel-glow bg-card/60 backdrop-blur-md h-fit ${manualPanel.className}`}
            style={manualPanel.style}
            onMouseEnter={manualPanel.onMouseEnter}
            onMouseLeave={manualPanel.onMouseLeave}
            onFocus={manualPanel.onFocus}
            onBlur={manualPanel.onBlur}
          >
            <div aria-hidden className={manualPanel.overlayClassName} />
            <CardHeader className="pb-3">
              <CardTitle className="text-base">
                <Localize i18n_default_text="Manual mode" />
              </CardTitle>
              <p className="text-xs font-semibold text-foreground/90">
                {activeSymbol?.underlying_symbol_name ?? localize('Select a market')}
              </p>
            </CardHeader>
            <CardContent>
              {botRunning && (
                <p className="text-xs text-amber-500 bg-amber-500/10 rounded-md px-2.5 py-1.5 mb-3">
                  <Localize i18n_default_text="Manual trading is paused while the robot is running." />
                </p>
              )}
              <fieldset disabled={botRunning} className="space-y-3 border-0 p-0 m-0 min-w-0 max-w-md">
                <div className="space-y-1.5">
                  <Label className="text-xs font-semibold text-foreground/90">
                    <Localize i18n_default_text="Trade Type" />
                  </Label>
                  <Select value={tradeType} onValueChange={(v) => setTradeType(v as TradeType)}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {tradeTypeOptions.map((opt) => (
                        <SelectItem key={opt.value} value={opt.value}>
                          {opt.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {tradeType !== 'even-odd' && (
                  <div className="space-y-1.5">
                    <Label className="text-xs font-semibold text-foreground/90">
                      <Localize i18n_default_text="Prediction" />
                    </Label>
                    <Select
                      value={String(selectedDigit)}
                      onValueChange={(v) => setSelectedDigit(parseInt(v, 10))}
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {Array.from({ length: 10 }, (_, d) => (
                          <SelectItem key={d} value={String(d)}>
                            {d}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                )}

                <TradeControls
                  tradeType={tradeType}
                  contractMode={contractMode}
                  onContractModeChange={setContractMode}
                  selectedDigit={selectedDigit}
                  isConnected={isConnected}
                  stake={stake}
                  onStakeChange={setStake}
                  duration={duration}
                  onDurationChange={setDuration}
                  durationLimits={durationLimits}
                  proposal={proposal}
                  isProposalLoading={isProposalLoading}
                  onBuy={buyContract}
                  isBuying={isBuying}
                  buyResult={buyResult}
                  buyError={buyError}
                  onClearBuyResult={clearBuyResult}
                  isAuthenticated={isAuthenticated}
                />
              </fieldset>
            </CardContent>
          </Card>
        </div>
      </div>
    </>
  );
}
