'use client';

import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { toast } from 'sonner';
import { Localize } from '@deriv-com/translations';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { SymbolSelector } from '@/components/custom/symbol-selector';
import { TradeControls } from '@/components/trade-controls';
import { PositionsTable } from '@/components/custom/positions-table';
import { cn } from '@/lib/utils';
import { useAppTranslations } from '@/components/custom/i18n-provider';
import { computeDigitStats, getLastDigit } from '@/lib/digit-stats';
import {
  useMinervaBot,
  type MinervaPhase,
  type MinervaTradingMode,
  type MinervaSide,
  type MinervaLogEntry,
} from '@/hooks/use-minerva-bot';
import { useIsMobile } from '@/hooks/use-is-mobile';
import type {
  ActiveSymbol,
  Tick,
  DurationLimits,
  ProposalInfo,
  BuyResult,
} from '@deriv/core';
import type {
  ContractMode,
  TradeType,
  DigitStats,
  OpenPosition,
  ClosedPosition,
} from '@/lib/types';

const DIGIT_CONTRACT_TYPES = [
  'DIGITMATCH',
  'DIGITDIFF',
  'DIGITOVER',
  'DIGITUNDER',
  'DIGITEVEN',
  'DIGITODD',
];

function getDigitContractLabels(
  localize: (text: string) => string
): Record<string, string> {
  return {
    DIGITMATCH: localize('Digit Match'),
    DIGITDIFF: localize('Digit Differs'),
    DIGITOVER: localize('Digit Over'),
    DIGITUNDER: localize('Digit Under'),
    DIGITEVEN: localize('Digit Even'),
    DIGITODD: localize('Digit Odd'),
  };
}

function getDigitTradeTypeOptions(
  localize: (text: string) => string
): { value: TradeType; label: string }[] {
  return [
    { value: 'matches-differs', label: localize('Matches/Differs') },
    { value: 'over-under', label: localize('Over/Under') },
    { value: 'even-odd', label: localize('Even/Odd') },
  ];
}

type Tab = 'chart' | 'digits' | 'trades' | 'logs';

export interface MinervaViewProps {
  isConnected: boolean;
  isAuthenticated: boolean;
  balanceLabel: string | null;

  symbols: ActiveSymbol[];
  activeSymbol: ActiveSymbol | null;
  selectSymbol: (symbol: string) => void;
  currentTick: Tick | null;
  /** Full tick-price history (includes pre-fetched history, not just live ticks). */
  prices: number[];
  pipSize: number;

  tradeType: TradeType;
  setTradeType: (type: TradeType) => void;
  contractMode: ContractMode;
  setContractMode: (mode: ContractMode) => void;
  selectedDigit: number;
  setSelectedDigit: (digit: number) => void;
  stake: string;
  setStake: (value: string) => void;
  duration: number;
  setDuration: (value: number) => void;
  durationLimits: DurationLimits;
  proposal: ProposalInfo | null;
  isProposalLoading: boolean;
  buyContract: () => Promise<void>;
  isBuying: boolean;
  buyResult: BuyResult | null;
  buyError: string | null;
  clearBuyResult: () => void;

  openPositions: OpenPosition[];
  closedPositions: ClosedPosition[];
  sellContract: (contractId: number, bidPrice: string) => Promise<void>;
  sellingId: number | null;
  sellError: string | null;
  clearSellError: () => void;
}

const HISTORY_WINDOW = 100;
const RECENT_DIGITS_SHOWN = 26;
const ROBOT_SETTINGS_STORAGE_KEY = 'centurium:robot-settings';

interface SavedRobotSettings {
  duration: number;
  raStreakCount: string;
  raConfirmationStreak: string;
  raInitialStake: string;
  raStakeMultiplier: string;
  raMartingaleAfterLosses: string;
  raTpIncrement: string;
  raCooldownSeconds: string;
  raTradingMode: MinervaTradingMode;
  raAccountTakeProfit: string;
  raAccountStopLoss: string;
}

// Same spring used for the equivalent glide animation on the standalone
// Digits page, so the motion feels identical across both pages.
const ROBOT_GLIDE_SPRING = { type: 'spring', stiffness: 340, damping: 30, mass: 0.7 } as const;

function DigitFrequencyRow({
  digitStats,
  selectedDigit,
  onSelect,
  lastDigit,
}: {
  digitStats: DigitStats;
  selectedDigit: number;
  onSelect: (digit: number) => void;
  /** The digit currently being generated by the live tick stream — when
   *  provided, a glowing pointer glides to whichever button this matches,
   *  matching the animation on the standalone Digits page. */
  lastDigit?: number | null;
}) {
  const maxPct = Math.max(...digitStats.percentages);
  const minPct = Math.min(...digitStats.percentages);
  return (
    <div className="grid grid-cols-5 sm:grid-cols-10 gap-2">
      {digitStats.percentages.map((pct, digit) => {
        const isSelected = digit === selectedDigit;
        const isCurrent = digit === lastDigit;
        const isHighest = digitStats.totalTicks > 0 && pct === maxPct;
        const isLowest = digitStats.totalTicks > 0 && pct === minPct;
        return (
          <button
            key={digit}
            onClick={() => onSelect(digit)}
            className={cn(
              'relative flex flex-col items-center gap-1 rounded-md border py-2 transition-all duration-200',
              isSelected ? 'border-destructive ring-1 ring-destructive' : 'border-border',
              'bg-muted/30 hover:bg-muted/60 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]'
            )}
          >
            {isCurrent && (
              <>
                {/* Caret — glides above whichever digit is currently live */}
                <motion.span
                  layoutId="robot-digit-pointer-caret-live"
                  transition={ROBOT_GLIDE_SPRING}
                  className="pointer-events-none absolute -top-2.5 left-1/2 h-0 w-0 -translate-x-1/2 border-x-[5px] border-t-[6px] border-x-transparent border-t-primary"
                />
                {/* Glow ring — glides to sit around the currently live digit */}
                <motion.span
                  layoutId="robot-digit-pointer-glow-live"
                  transition={ROBOT_GLIDE_SPRING}
                  className="pointer-events-none absolute -inset-0.5 rounded-md ring-2 ring-primary shadow-[0_0_14px_2px] shadow-primary/50"
                />
              </>
            )}
            <span className="text-lg font-bold text-foreground">{digit}</span>
            <span
              className={cn(
                'text-xs font-mono font-bold',
                isHighest && 'text-amber-300',
                isLowest && 'text-rose-400',
                !isHighest && !isLowest && 'text-foreground/80'
              )}
            >
              {pct.toFixed(1)}%
            </span>
          </button>
        );
      })}
    </div>
  );
}

function DigitHistogram({ title, stats }: { title: string; stats: DigitStats }) {
  const maxPct = Math.max(...stats.percentages, 1);
  const highest = Math.max(...stats.percentages);
  const lowest = Math.min(...stats.percentages);
  return (
    <div className="flex flex-col gap-2">
      <span className="text-xs font-semibold text-foreground/90">{title}</span>
      <div className="flex items-end gap-1 h-28">
        {stats.percentages.map((pct, digit) => {
          const isHighest = stats.totalTicks > 0 && pct === highest;
          const isLowest = stats.totalTicks > 0 && pct === lowest;
          return (
            <div
              key={digit}
              className="flex-1 flex flex-col items-center gap-1 rounded-md py-1 transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]"
            >
              <span
                className={cn(
                  'text-[10px] font-bold',
                  isHighest ? 'text-primary' : isLowest ? 'text-rose-400' : 'text-foreground/80'
                )}
              >
                {stats.totalTicks > 0 ? `${Math.round(pct)}%` : ''}
              </span>
              <div className="w-full h-20 flex items-end">
                <div
                  className={cn(
                    'w-full rounded-sm',
                    isHighest ? 'bg-primary' : isLowest ? 'bg-rose-500/70' : 'bg-muted-foreground/50'
                  )}
                  style={{ height: `${Math.max((pct / maxPct) * 100, 3)}%` }}
                />
              </div>
              <span className="text-[10px] font-semibold text-foreground/80">{digit}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function TickSparkline({ prices }: { prices: number[] }) {
  const points = prices.slice(-24);
  if (points.length < 2) {
    return (
      <div className="h-24 flex items-center justify-center text-xs font-semibold text-foreground/90">
        <Localize i18n_default_text="Waiting for enough ticks…" />
      </div>
    );
  }
  const min = Math.min(...points);
  const max = Math.max(...points);
  const range = max - min || 1;
  const w = 600;
  const h = 90;
  const coords = points.map((p, i) => {
    const x = (i / (points.length - 1)) * w;
    const y = h - ((p - min) / range) * (h - 16) - 8;
    return [x, y] as const;
  });
  const path = coords.map(([x, y], i) => `${i === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`).join(' ');
  return (
    <svg viewBox={`0 0 ${w} ${h}`} className="w-full h-24" preserveAspectRatio="none">
      <path d={path} fill="none" stroke="currentColor" className="text-primary" strokeWidth={2} />
      {coords.map(([x, y], i) => {
        const isLast = i === coords.length - 1;
        return (
          <circle
            key={i}
            cx={x}
            cy={y}
            r={isLast ? 4 : 2.5}
            className={isLast ? 'fill-primary' : 'fill-amber-300/80'}
          />
        );
      })}
    </svg>
  );
}

function raSideLabel(side: MinervaSide, localize: (t: string) => string): string {
  if (side === 'over4') return localize('Over 4');
  if (side === 'under5') return localize('Under 5');
  return '';
}

function getRaStatusLabel(
  phase: MinervaPhase,
  armedSide: MinervaSide,
  confirmProgress: number,
  confirmationStreak: string,
  localize: (t: string) => string,
  burstActive?: boolean,
  burstPnl?: number
): string {
  switch (phase) {
    case 'awaiting-proposal':
    case 'awaiting-buy':
      return burstActive
        ? `${localize('Placing trade…')} (${(burstPnl ?? 0) >= 0 ? '+' : ''}${(burstPnl ?? 0).toFixed(2)})`
        : localize('Placing trade…');
    case 'awaiting-settlement':
      return burstActive
        ? `${localize('Trade running…')} (${(burstPnl ?? 0) >= 0 ? '+' : ''}${(burstPnl ?? 0).toFixed(2)})`
        : localize('Trade running…');
    default:
      if (armedSide) {
        return `${raSideLabel(armedSide, localize)} ${localize('ARMED')} — ${localize(
          'waiting for confirmation streak'
        )} (${confirmProgress}/${confirmationStreak})`;
      }
      return localize('Watching…');
  }
}

function getRaStoppedLabel(
  reason: 'manual' | 'take-profit' | 'stop-loss' | null,
  localize: (t: string) => string
): string | null {
  switch (reason) {
    case 'manual':
      return localize('Stopped: Manual');
    case 'take-profit':
      return localize('Stopped: Take Profit');
    case 'stop-loss':
      return localize('Stopped: Stop Loss');
    default:
      return null;
  }
}

/** Transient note shown while Minerva is still running but idle between bursts,
 *  explaining how the last burst ended before a new signal opens the next one. */
function getRaLastBurstLabel(
  outcome: 'take-profit' | 'stop-loss' | 'error' | null,
  localize: (t: string) => string
): string | null {
  switch (outcome) {
    case 'take-profit':
      return localize('Last run hit its Take Profit — watching for the next signal.');
    case 'stop-loss':
      return localize('Last run hit its Stop Loss — watching for the next signal.');
    case 'error':
      return localize('Last trade failed — watching for the next signal.');
    default:
      return null;
  }
}

/** Small strip of the last digits seen while Minerva was on — oldest to newest,
 *  over4 (5-9) and under5 (0-4) colored differently, newest highlighted.
 *  Native equivalent of the extension's popup "Digit Record". */
function RaDigitRecord({ digits }: { digits: number[] }) {
  if (digits.length === 0) return null;
  return (
    <div className="flex flex-wrap gap-1 rounded-md bg-muted/30 p-2">
      {digits.map((d, i) => {
        const isOver4 = d > 4;
        const isNewest = i === digits.length - 1;
        return (
          <span
            key={i}
            className={cn(
              'flex h-5 w-5 items-center justify-center rounded text-[10px] font-bold tabular-nums',
              isOver4 ? 'bg-emerald-500/25 text-emerald-400' : 'bg-rose-500/25 text-rose-400',
              isNewest && 'ring-2 ring-primary'
            )}
          >
            {d}
          </span>
        );
      })}
    </div>
  );
}

type RobotPanelKey = 'settings' | 'analysis' | 'manual';

/**
 * Same premium hover micro-interaction used on the homepage's entry cards:
 * the hovered panel lifts/scales up and its `.panel-glow` breathing glow
 * gets a brighter overlay faded in on top (rather than swapping the
 * keyframes, which would make the glow jump instead of smoothly
 * intensifying). The other panels dim slightly while one is hovered.
 */
function useRobotPanelHover() {
  const [hovered, setHovered] = useState<RobotPanelKey | null>(null);

  function panelProps(key: RobotPanelKey) {
    const isHovered = hovered === key;
    const isDimmed = hovered !== null && hovered !== key;
    return {
      onMouseEnter: () => setHovered(key),
      onMouseLeave: () =>
        setHovered((current: RobotPanelKey | null) => (current === key ? null : current)),
      onFocus: () => setHovered(key),
      onBlur: () =>
        setHovered((current: RobotPanelKey | null) => (current === key ? null : current)),
      style: {
        transform: isHovered ? 'translateY(-4px) scale(1.02)' : 'translateY(0) scale(1)',
        opacity: isDimmed ? 0.92 : 1,
      },
      className:
        'relative transition-[transform,opacity] duration-300 ease-out will-change-transform',
      overlayClassName:
        'pointer-events-none absolute inset-0 rounded-[inherit] transition-opacity duration-300 ease-out shadow-[0_14px_32px_-12px_rgba(0,0,0,0.35),0_0_0_1px_rgba(59,130,246,0.55),0_0_26px_4px_rgba(59,130,246,0.45),0_0_56px_14px_rgba(59,130,246,0.22)]' +
        (isHovered ? ' opacity-100' : ' opacity-0'),
    };
  }

  return panelProps;
}

/** Which side panel is currently open. The two are mutually exclusive —
 *  opening one always collapses the other, and the Digit panel in between
 *  is never collapsed, only pushed left/right by the resulting resize. */
type OpenSide = 'automated' | 'manual';

// Widths for the two side panels (desktop/lg only — on mobile both panels
// are always shown at full width, stacked, since there's no horizontal
// space to fight over there).
const AUTOMATED_OPEN_WIDTH = 420;
const MANUAL_OPEN_WIDTH = 300;
const SIDE_COLLAPSED_WIDTH = 40;

/**
 * A side panel (Automated Robot or Manual) that can collapse down to a
 * thin strip showing only a subtle arrow. This behaves like a real
 * sliding drawer: the panel's content stays mounted and fully visible at
 * all times — nothing fades or swaps — while the wrapper's *width*
 * animates continuously between its open and collapsed size. A
 * `clip-path` on the wrapper reveals/hides the content as that width
 * changes, so the whole thing reads as one continuous slide rather than
 * a pop-in/vanish.
 *
 * `clip-path` is used instead of `overflow-hidden` deliberately: unlike
 * `overflow`, it doesn't establish a new scroll/containing context, so it
 * won't interfere with the Automated panel's `position: sticky` scroll
 * behavior.
 *
 * All of the panel's actual data (form values, selections, etc.) lives in
 * state one level up in `MinervaView` — the Card here is a plain
 * presentation of that state — so keeping it mounted while collapsed
 * costs nothing and there's no state to lose.
 */
function CollapsibleSidePanel({
  isMobile,
