'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { toast } from 'sonner';
import { Localize } from '@deriv-com/translations';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { SymbolSelector } from '@/components/custom/symbol-selector';
import { TradeControls } from '@/components/trade-controls';
import { PositionsTable } from '@/components/custom/positions-table';
import { cn } from '@/lib/utils';
import { useAppTranslations } from '@/components/custom/i18n-provider';
import { computeDigitStats, getLastDigit } from '@/lib/digit-stats';
import type {
  ActiveSymbol,
  Tick,
  DurationLimits,
  ProposalInfo,
  BuyResult,
} from '@deriv/core';
import type {
  ContractMode,
  TradeType,
  DigitStats,
  OpenPosition,
  ClosedPosition,
} from '@/lib/types';

const DIGIT_CONTRACT_TYPES = [
  'DIGITMATCH',
  'DIGITDIFF',
  'DIGITOVER',
  'DIGITUNDER',
  'DIGITEVEN',
  'DIGITODD',
];

function getDigitContractLabels(
  localize: (text: string) => string
): Record<string, string> {
  return {
    DIGITMATCH: localize('Digit Match'),
    DIGITDIFF: localize('Digit Differs'),
    DIGITOVER: localize('Digit Over'),
    DIGITUNDER: localize('Digit Under'),
    DIGITEVEN: localize('Digit Even'),
    DIGITODD: localize('Digit Odd'),
  };
}

function getDigitTradeTypeOptions(
  localize: (text: string) => string
): { value: TradeType; label: string }[] {
  return [
    { value: 'matches-differs', label: localize('Matches/Differs') },
    { value: 'over-under', label: localize('Over/Under') },
    { value: 'even-odd', label: localize('Even/Odd') },
  ];
}

type Tab = 'chart' | 'digits' | 'trades' | 'logs';

export interface TradeRobotViewProps {
  isConnected: boolean;
  isAuthenticated: boolean;
  balanceLabel: string | null;

  symbols: ActiveSymbol[];
  activeSymbol: ActiveSymbol | null;
  selectSymbol: (symbol: string) => void;
  currentTick: Tick | null;
  pipSize: number;

  tradeType: TradeType;
  setTradeType: (type: TradeType) => void;
  contractMode: ContractMode;
  setContractMode: (mode: ContractMode) => void;
  selectedDigit: number;
  setSelectedDigit: (digit: number) => void;
  stake: string;
  setStake: (value: string) => void;
  duration: number;
  setDuration: (value: number) => void;
  durationLimits: DurationLimits;
  proposal: ProposalInfo | null;
  isProposalLoading: boolean;
  buyContract: () => Promise<void>;
  isBuying: boolean;
  buyResult: BuyResult | null;
  buyError: string | null;
  clearBuyResult: () => void;

  openPositions: OpenPosition[];
  closedPositions: ClosedPosition[];
  sellContract: (contractId: number, bidPrice: string) => Promise<void>;
  sellingId: number | null;
  sellError: string | null;
  clearSellError: () => void;
}

const HISTORY_WINDOW = 100;
const RECENT_DIGITS_SHOWN = 26;

// Shared spring used for every "glide" animation on this page (the digit
// pointer, its caret, and the most-recent-digits strip) so all the motion
// feels like one cohesive system rather than several different easings.
const GLIDE_SPRING = { type: 'spring', stiffness: 340, damping: 30, mass: 0.7 } as const;

function DigitFrequencyRow({
  digitStats,
  selectedDigit,
  lastDigit,
  onSelect,
}: {
  digitStats: DigitStats;
  selectedDigit: number;
  /** The digit currently being generated by the live tick stream — the
   *  glowing pointer glides to whichever button this matches. */
  lastDigit: number | null;
  onSelect: (digit: number) => void;
}) {
  const maxPct = Math.max(...digitStats.percentages);
  const minPct = Math.min(...digitStats.percentages);
  return (
    <div className="grid grid-cols-5 sm:grid-cols-10 gap-2 pt-2.5">
      {digitStats.percentages.map((pct, digit) => {
        const isSelected = digit === selectedDigit;
        const isCurrent = digit === lastDigit;
        const isHighest = digitStats.totalTicks > 0 && pct === maxPct;
        const isLowest = digitStats.totalTicks > 0 && pct === minPct;
        return (
          <button
            key={digit}
            onClick={() => onSelect(digit)}
            className={cn(
              'relative flex flex-col items-center gap-1 rounded-md border py-2 transition-colors',
              isSelected
                ? 'border-destructive ring-1 ring-destructive'
                : isHighest
                  ? 'border-emerald-500/60'
                  : 'border-border',
              'bg-muted/30 hover:bg-muted/60'
            )}
          >
            {isCurrent && (
              <>
                {/* Caret — glides above whichever digit is currently live */}
                <motion.span
                  layoutId="digit-pointer-caret"
                  transition={GLIDE_SPRING}
                  className="pointer-events-none absolute -top-2.5 left-1/2 h-0 w-0 -translate-x-1/2 border-x-[5px] border-t-[6px] border-x-transparent border-t-primary"
                />
                {/* Glow ring — glides to sit around the currently live digit */}
                <motion.span
                  layoutId="digit-pointer-glow"
                  transition={GLIDE_SPRING}
                  className="pointer-events-none absolute -inset-0.5 rounded-lg ring-2 ring-primary shadow-[0_0_14px_2px] shadow-primary/50"
                />
              </>
            )}
            <span className="text-base font-semibold">{digit}</span>
            <span
              className={cn(
                'text-[11px] font-mono',
                isHighest && 'text-emerald-500 font-semibold',
                isLowest && 'text-rose-500 font-semibold',
                !isHighest && !isLowest && 'text-muted-foreground'
              )}
            >
              {pct.toFixed(1)}%
            </span>
          </button>
        );
      })}
    </div>
  );
}

function DigitHistogram({ title, stats }: { title: string; stats: DigitStats }) {
  const maxPct = Math.max(...stats.percentages, 1);
  const highest = Math.max(...stats.percentages);
  const lowest = Math.min(...stats.percentages);
  return (
    <div className="flex flex-col gap-2">
      <span className="text-xs text-muted-foreground">{title}</span>
      <div className="flex items-end gap-1 h-28">
        {stats.percentages.map((pct, digit) => {
          const isHighest = stats.totalTicks > 0 && pct === highest;
          const isLowest = stats.totalTicks > 0 && pct === lowest;
          return (
            <div key={digit} className="flex-1 flex flex-col items-center gap-1">
              <span className="text-[9px] text-muted-foreground">
                {stats.totalTicks > 0 ? `${Math.round(pct)}%` : ''}
              </span>
              <div className="w-full h-20 flex items-end">
                <div
                  className={cn(
                    'w-full rounded-sm',
                    isHighest ? 'bg-emerald-500' : isLowest ? 'bg-rose-500/70' : 'bg-muted-foreground/30'
                  )}
                  style={{ height: `${Math.max((pct / maxPct) * 100, 3)}%` }}
                />
              </div>
              <span className="text-[9px] text-muted-foreground">{digit}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function TickSparkline({ prices }: { prices: number[] }) {
  const points = prices.slice(-24);
  if (points.length < 2) {
    return (
      <div className="h-24 flex items-center justify-center text-xs text-muted-foreground">
        <Localize i18n_default_text="Waiting for enough ticks…" />
      </div>
    );
  }
  const min = Math.min(...points);
  const max = Math.max(...points);
  const range = max - min || 1;
  const w = 600;
  const h = 90;
  const coords = points.map((p, i) => {
    const x = (i / (points.length - 1)) * w;
    const y = h - ((p - min) / range) * (h - 16) - 8;
    return [x, y] as const;
  });
  const path = coords.map(([x, y], i) => `${i === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`).join(' ');
  return (
    <svg viewBox={`0 0 ${w} ${h}`} className="w-full h-24" preserveAspectRatio="none">
      <path d={path} fill="none" stroke="currentColor" className="text-primary" strokeWidth={2} />
      {coords.map(([x, y], i) => {
        const isLast = i === coords.length - 1;
        const isUp = i > 0 && points[i] >= points[i - 1];
        return (
          <circle
            key={i}
            cx={x}
            cy={y}
            r={isLast ? 4 : 2.5}
            className={isUp ? 'fill-emerald-500' : 'fill-rose-500'}
          />
        );
      })}
    </svg>
  );
}

export function TradeRobotView({
  isConnected,
  isAuthenticated,
  balanceLabel,
  symbols,
  activeSymbol,
  selectSymbol,
  currentTick,
  pipSize,
  tradeType,
  setTradeType,
  contractMode,
  setContractMode,
  selectedDigit,
  setSelectedDigit,
  stake,
  setStake,
  duration,
  setDuration,
  durationLimits,
  proposal,
  isProposalLoading,
  buyContract,
  isBuying,
  buyResult,
  buyError,
  clearBuyResult,
  openPositions,
  closedPositions,
  sellContract,
  sellingId,
  sellError,
  clearSellError,
}: TradeRobotViewProps) {
  const { localize } = useAppTranslations();
  const digitTradeTypeOptions = getDigitTradeTypeOptions(localize);
  const digitContractLabels = getDigitContractLabels(localize);

  const [activeTab, setActiveTab] = useState<Tab>('digits');
  const [priceHistory, setPriceHistory] = useState<number[]>([]);

  // Same digits as priceHistory, but paired with a stable per-tick id so the
  // "Most recent digits" strip can animate entries gliding in/along instead
  // of snapping — an index-based key would misidentify which square is
  // actually new as the window slides.
  const digitLogIdRef = useRef(0);
  const [digitLog, setDigitLog] = useState<{ id: number; digit: number }[]>([]);

  // Local, informational bot-settings state. There is no automated execution
  // engine wired up yet — starting the robot only shows a notice below.
  const [multiplier, setMultiplier] = useState('2.5');
  const [virtualLosses, setVirtualLosses] = useState('0');
  const [startWithVirtual, setStartWithVirtual] = useState(true);
  const [analyzeAmount, setAnalyzeAmount] = useState('100');
  const [reanalyzeAfter, setReanalyzeAfter] = useState('2');
  const [initialAmount, setInitialAmount] = useState('1');
  const [targetProfit, setTargetProfit] = useState('5');
  const [stopLossMultiplier, setStopLossMultiplier] = useState('6');

  // Reset the rolling tick buffer whenever the active market changes.
  useEffect(() => {
    setPriceHistory([]);
    setDigitLog([]);
  }, [activeSymbol?.underlying_symbol]);

  useEffect(() => {
    if (currentTick) {
      digitLogIdRef.current += 1;
      const id = digitLogIdRef.current;
      const digit = getLastDigit(currentTick.quote, pipSize);
      setDigitLog((prev) => {
        const next = [...prev, { id, digit }];
        return next.length > RECENT_DIGITS_SHOWN ? next.slice(-RECENT_DIGITS_SHOWN) : next;
      });
    }
  }, [currentTick, pipSize]);

  useEffect(() => {
    if (currentTick) {
      setPriceHistory((prev) => {
        const next = [...prev, currentTick.quote];
        return next.length > HISTORY_WINDOW ? next.slice(-HISTORY_WINDOW) : next;
      });
    }
  }, [currentTick]);

  const overallStats = useMemo(
    () => computeDigitStats(priceHistory, pipSize),
    [priceHistory, pipSize]
  );
  const last25 = useMemo(
    () => computeDigitStats(priceHistory.slice(-25), pipSize),
    [priceHistory, pipSize]
  );
  const last50 = useMemo(
    () => computeDigitStats(priceHistory.slice(-50), pipSize),
    [priceHistory, pipSize]
  );
  const last100 = useMemo(
    () => computeDigitStats(priceHistory.slice(-100), pipSize),
    [priceHistory, pipSize]
  );
  // The digit currently being generated — drives the gliding pointer on the
  // frequency grid and the highlighted square in the recent-digits strip.
  const lastDigit = digitLog.length > 0 ? digitLog[digitLog.length - 1].digit : null;

  const handleStart = () => {
    toast.info(localize('Bot settings saved'), {
      description: localize(
        "These settings are stored here for reference, but this build doesn't include an automated trading engine yet — use Manual mode to place trades with the connection you have configured."
      ),
    });
  };

  return (
    <div className="w-full max-w-[1600px] mx-auto px-3 py-4 sm:px-4 grid grid-cols-1 lg:grid-cols-[280px_1fr_300px] gap-4">
      {/* Left: Robot settings */}
      <Card className="h-fit bg-card/60 backdrop-blur-md">
        <CardHeader className="pb-3">
          <CardTitle className="text-base">
            <Localize i18n_default_text="Robot settings" />
          </CardTitle>
          <p className="text-xs text-muted-foreground">
            {isConnected ? (
              balanceLabel ? (
                balanceLabel
              ) : (
                <Localize i18n_default_text="Connected" />
              )
            ) : (
              <Localize i18n_default_text="Not connected" />
            )}
          </p>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-1.5">
            <Label className="text-xs text-muted-foreground">
              <Localize i18n_default_text="Market" />
            </Label>
            <SymbolSelector
              symbols={symbols}
              activeSymbol={activeSymbol}
              onSymbolChange={selectSymbol}
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <Label className="text-xs text-muted-foreground">
                <Localize i18n_default_text="Trade Type" />
              </Label>
              <Select value={tradeType} onValueChange={(v) => setTradeType(v as TradeType)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {digitTradeTypeOptions.map((opt) => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs text-muted-foreground">
                <Localize i18n_default_text="Prediction" />
              </Label>
              {tradeType === 'even-odd' ? (
                <Input value={contractMode === 'DIGITEVEN' ? 'Even' : 'Odd'} disabled fullWidth />
              ) : (
                <Select
                  value={String(selectedDigit)}
                  onValueChange={(v) => setSelectedDigit(parseInt(v, 10))}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {Array.from({ length: 10 }, (_, d) => (
                      <SelectItem key={d} value={String(d)}>
                        {d}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <Label className="text-xs text-muted-foreground">
                <Localize i18n_default_text="Duration" />
              </Label>
              <Input
                type="number"
                value={duration}
                onChange={(e) => {
                  const val = parseInt(e.target.value, 10);
                  if (!isNaN(val)) setDuration(val);
                }}
                min={durationLimits.min}
                max={durationLimits.max}
                labelRight={localize('Ticks')}
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs text-muted-foreground">
                <Localize i18n_default_text="Multiplier" />
              </Label>
              <Input value={multiplier} onChange={(e) => setMultiplier(e.target.value)} />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <Label className="text-xs text-muted-foreground">
                <Localize i18n_default_text="Virtual losses" />
              </Label>
              <Input value={virtualLosses} onChange={(e) => setVirtualLosses(e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs text-muted-foreground">
                <Localize i18n_default_text="Start with virtual" />
              </Label>
              <Select
                value={startWithVirtual ? 'yes' : 'no'}
                onValueChange={(v) => setStartWithVirtual(v === 'yes')}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="yes">{localize('Yes')}</SelectItem>
                  <SelectItem value="no">{localize('No')}</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <Label className="text-xs text-muted-foreground">
                <Localize i18n_default_text="Analyze amount" />
              </Label>
              <Input value={analyzeAmount} onChange={(e) => setAnalyzeAmount(e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs text-muted-foreground">
                <Localize i18n_default_text="Reanalyze after losses" />
              </Label>
              <Input value={reanalyzeAfter} onChange={(e) => setReanalyzeAfter(e.target.value)} />
            </div>
          </div>

          <div className="border-t border-border pt-3 grid grid-cols-3 gap-2">
            <div className="space-y-1.5">
              <Label className="text-xs text-muted-foreground">
                <Localize i18n_default_text="Initial" />
              </Label>
              <Input value={initialAmount} onChange={(e) => setInitialAmount(e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs text-muted-foreground">
                <Localize i18n_default_text="Target profit" />
              </Label>
              <Input value={targetProfit} onChange={(e) => setTargetProfit(e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs text-muted-foreground">
                <Localize i18n_default_text="Stop loss ×" />
              </Label>
              <Input value={stopLossMultiplier} onChange={(e) => setStopLossMultiplier(e.target.value)} />
            </div>
          </div>

          <Button className="w-full" size="lg" onClick={handleStart}>
            <Localize i18n_default_text="Start" />
          </Button>
          <p className="text-[11px] text-muted-foreground text-center">
            <Localize i18n_default_text="These settings are for reference only — automated execution isn't implemented in this build." />
          </p>
        </CardContent>
      </Card>

      {/* Center: analysis */}
      <Card className="h-fit bg-card/60 backdrop-blur-md">
        <CardHeader className="pb-0">
          <div className="flex items-center gap-5 border-b border-border">
            {(
              [
                ['chart', localize('Chart')],
                ['digits', localize('Digits')],
                ['trades', localize('Trades')],
                ['logs', localize('Logs')],
              ] as [Tab, string][]
            ).map(([key, label]) => (
              <button
                key={key}
                onClick={() => setActiveTab(key)}
                className={cn(
                  'pb-2.5 text-sm font-medium border-b-2 -mb-px transition-colors',
                  activeTab === key
                    ? 'border-primary text-foreground'
                    : 'border-transparent text-muted-foreground hover:text-foreground'
                )}
              >
                {label}
              </button>
            ))}
          </div>
        </CardHeader>
        <CardContent className="pt-4 space-y-6">
          {activeTab === 'digits' && (
            <>
              <div className="space-y-2">
                <p className="text-center text-sm font-medium">
                  <Localize i18n_default_text="Digits frequency percentage" />
                </p>
                <DigitFrequencyRow
                  digitStats={overallStats}
                  selectedDigit={selectedDigit}
                  lastDigit={lastDigit}
                  onSelect={setSelectedDigit}
                />
              </div>

              <div className="space-y-2">
                <p className="text-sm font-medium">
                  <Localize i18n_default_text="Most recent digits" />
                </p>
                <div className="flex flex-wrap gap-1.5">
                  {digitLog.length === 0 && (
                    <span className="text-xs text-muted-foreground">
                      <Localize i18n_default_text="Waiting for ticks…" />
                    </span>
                  )}
                  <AnimatePresence initial={false}>
                    {digitLog.map((entry, i) => {
                      const isLast = i === digitLog.length - 1;
                      return (
                        <motion.span
                          key={entry.id}
                          layout
                          initial={{ opacity: 0, y: -8, scale: 0.75 }}
                          animate={{ opacity: 1, y: 0, scale: 1 }}
                          exit={{ opacity: 0, scale: 0.75 }}
                          transition={GLIDE_SPRING}
                          className={cn(
                            'flex h-7 w-7 items-center justify-center rounded-md text-xs font-semibold transition-colors duration-500',
                            isLast
                              ? 'bg-primary text-primary-foreground'
                              : 'bg-muted text-muted-foreground'
                          )}
                        >
                          {entry.digit}
                        </motion.span>
                      );
                    })}
                  </AnimatePresence>
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <DigitHistogram title={localize('Last 25 digits')} stats={last25} />
                <DigitHistogram title={localize('Last 50 digits')} stats={last50} />
                <DigitHistogram title={localize('Last 100 digits')} stats={last100} />
              </div>

              <div className="space-y-2">
                <p className="text-sm font-medium">
                  <Localize i18n_default_text="Recent ticks" />
                </p>
                <TickSparkline prices={priceHistory} />
              </div>
            </>
          )}

          {activeTab === 'chart' && (
            <div className="py-10 text-center text-sm text-muted-foreground">
              <Localize i18n_default_text="A full price chart isn't wired into this view yet — the live spot and recent ticks are shown on the Digits tab." />
            </div>
          )}

          {activeTab === 'trades' && (
            <>
              {isAuthenticated ? (
                <PositionsTable
                  openPositions={openPositions.filter((p) => DIGIT_CONTRACT_TYPES.includes(p.contract_type))}
                  closedPositions={closedPositions.filter((p) => DIGIT_CONTRACT_TYPES.includes(p.contract_type))}
                  onSell={sellContract}
                  sellingId={sellingId}
                  sellError={sellError}
                  onClearSellError={clearSellError}
                  contractTypeLabels={digitContractLabels}
                  className="mt-0"
                />
              ) : (
                <div className="py-10 text-center text-sm text-muted-foreground">
                  <Localize i18n_default_text="Log in to see your open and closed positions." />
                </div>
              )}
            </>
          )}

          {activeTab === 'logs' && (
            <div className="py-10 text-center text-sm text-muted-foreground">
              <Localize i18n_default_text="No bot execution logs yet — this build doesn't run an automated strategy loop." />
            </div>
          )}
        </CardContent>
      </Card>

      {/* Right: Manual mode */}
      <Card className="h-fit bg-card/60 backdrop-blur-md">
        <CardHeader className="pb-3">
          <CardTitle className="text-base">
            <Localize i18n_default_text="Manual mode" />
          </CardTitle>
          <p className="text-xs text-muted-foreground">
            {activeSymbol?.underlying_symbol_name ?? localize('Select a market')}
          </p>
        </CardHeader>
        <CardContent>
          <TradeControls
            tradeType={tradeType}
            contractMode={contractMode}
            onContractModeChange={setContractMode}
            selectedDigit={selectedDigit}
            isConnected={isConnected}
            stake={stake}
            onStakeChange={setStake}
            duration={duration}
            onDurationChange={setDuration}
            durationLimits={durationLimits}
            proposal={proposal}
            isProposalLoading={isProposalLoading}
            onBuy={buyContract}
            isBuying={isBuying}
            buyResult={buyResult}
            buyError={buyError}
            onClearBuyResult={clearBuyResult}
            isAuthenticated={isAuthenticated}
          />
        </CardContent>
      </Card>
    </div>
  );
}
