'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { toast } from 'sonner';
import { Localize } from '@deriv-com/translations';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { SymbolSelector } from '@/components/custom/symbol-selector';
import { TradeControls } from '@/components/trade-controls';
import { PositionsTable } from '@/components/custom/positions-table';
import { cn } from '@/lib/utils';
import { useAppTranslations } from '@/components/custom/i18n-provider';
import { computeDigitStats, getLastDigit } from '@/lib/digit-stats';
import type {
  ActiveSymbol,
  Tick,
  DurationLimits,
  ProposalInfo,
  BuyResult,
} from '@deriv/core';
import type {
  ContractMode,
  TradeType,
  DigitStats,
  OpenPosition,
  ClosedPosition,
} from '@/lib/types';

const DIGIT_CONTRACT_TYPES = [
  'DIGITMATCH',
  'DIGITDIFF',
  'DIGITOVER',
  'DIGITUNDER',
  'DIGITEVEN',
  'DIGITODD',
];

function getDigitContractLabels(
  localize: (text: string) => string
): Record<string, string> {
  return {
    DIGITMATCH: localize('Digit Match'),
    DIGITDIFF: localize('Digit Differs'),
    DIGITOVER: localize('Digit Over'),
    DIGITUNDER: localize('Digit Under'),
    DIGITEVEN: localize('Digit Even'),
    DIGITODD: localize('Digit Odd'),
  };
}

function getDigitTradeTypeOptions(
  localize: (text: string) => string
): { value: TradeType; label: string }[] {
  return [
    { value: 'matches-differs', label: localize('Matches/Differs') },
    { value: 'over-under', label: localize('Over/Under') },
    { value: 'even-odd', label: localize('Even/Odd') },
  ];
}

type Tab = 'chart' | 'digits' | 'trades' | 'logs';

export interface TradeRobotViewProps {
  isConnected: boolean;
  isAuthenticated: boolean;
  balanceLabel: string | null;

  symbols: ActiveSymbol[];
  activeSymbol: ActiveSymbol | null;
  selectSymbol: (symbol: string) => void;
  currentTick: Tick | null;
  pipSize: number;

  tradeType: TradeType;
  setTradeType: (type: TradeType) => void;
  contractMode: ContractMode;
  setContractMode: (mode: ContractMode) => void;
  selectedDigit: number;
  setSelectedDigit: (digit: number) => void;
  stake: string;
  setStake: (value: string) => void;
  duration: number;
  setDuration: (value: number) => void;
  durationLimits: DurationLimits;
  proposal: ProposalInfo | null;
  isProposalLoading: boolean;
  buyContract: () => Promise<void>;
  isBuying: boolean;
  buyResult: BuyResult | null;
  buyError: string | null;
  clearBuyResult: () => void;

  openPositions: OpenPosition[];
  closedPositions: ClosedPosition[];
  sellContract: (contractId: number, bidPrice: string) => Promise<void>;
  sellingId: number | null;
  sellError: string | null;
  clearSellError: () => void;
}

const HISTORY_WINDOW = 100;
const RECENT_DIGITS_SHOWN = 26;

// Shared spring used for every "glide" animation on this page (the digit
// pointer, its caret, and the most-recent-digits strip) so all the motion
// feels like one cohesive system rather than several different easings.
const GLIDE_SPRING = { type: 'spring', stiffness: 340, damping: 30, mass: 0.7 } as const;

function DigitFrequencyRow({
  digitStats,
  selectedDigit,
  lastDigit,
  onSelect,
}: {
  digitStats: DigitStats;
  selectedDigit: number;
  /** The digit currently being generated by the live tick stream — the
   *  glowing pointer glides to whichever button this matches. */
  lastDigit: number | null;
  onSelect: (digit: number) => void;
}) {
  const maxPct = Math.max(...digitStats.percentages);
  const minPct = Math.min(...digitStats.percentages);
  return (
    <div className="grid grid-cols-5 sm:grid-cols-10 gap-2 pt-2.5">
      {digitStats.percentages.map((pct, digit) => {
        const isSelected = digit === selectedDigit;
        const isCurrent = digit === lastDigit;
        const isHighest = digitStats.totalTicks > 0 && pct === maxPct;
        const isLowest = digitStats.totalTicks > 0 && pct === minPct;
        return (
          <button
            key={digit}
            onClick={() => onSelect(digit)}
            className={cn(
              'relative flex flex-col items-center gap-1 rounded-md border py-2 transition-colors',
              isSelected
                ? 'border-destructive ring-1 ring-destructive'
                : isHighest
                  ? 'border-emerald-500/60'
                  : 'border-border',
              'bg-muted/30 hover:bg-muted/60'
            )}
          >
            {isCurrent && (
              <>
                {/* Caret — glides above whichever digit is currently live */}
                <motion.span
                  layoutId="digit-pointer-caret"
                  transition={GLIDE_SPRING}
                  className="pointer-events-none absolute -top-2.5 left-1/2 h-0 w-0 -translate-x-1/2 border-x-[5px] border-t-[6px] border-x-transparent border-t-primary"
                />
                {/* Glow ring — glides to sit around the currently live digit */}
                <motion.span
                  layoutId="digit-pointer-glow"
                  transition={GLIDE_SPRING}
                  className="pointer-events-none absolute -inset-0.5 rounded-lg ring-2 ring-primary shadow-[0_0_14px_2px] shadow-primary/50"
                />
              </>
            )}
            <span className="text-base font-semibold">{digit}</span>
            <span
              className={cn(
                'text-[11px] font-mono',
                isHighest && 'text-emerald-500 font-semibold',
                isLowest && 'text-rose-500 font-semibold',
                !isHighest && !isLowest && 'text-muted-foreground'
              )}
            >
              {pct.toFixed(1)}%
            </span>
          </button>
        );
      })}
    </div>
  );
}

function DigitHistogram({ title, stats }: { title: string; stats: DigitStats }) {
  const maxPct = Math.max(...stats.percentages, 1);
  const highest = Math.max(...stats.percentages);
  const lowest = Math.min(...stats.percentages);
  return (
    <div className="flex flex-col gap-2">
      <span className="text-xs text-muted-foreground">{title}</span>
      <div className="flex items-end gap-1 h-28">
        {stats.percentages.map((pct, digit) => {
          const isHighest = stats.totalTicks > 0 && pct === highest;
          const isLowest = stats.totalTicks > 0 && pct === lowest;
          return (
            <div key={digit} className="flex-1 flex flex-col items-center gap-1">
              <span className="text-[9px] text-muted-foreground">
                {stats.totalTicks > 0 ? `${Math.round(pct)}%` : ''}
              </span>
              <div className="w-full h-20 flex items-end">
                <div
                  className={cn(
                    'w-full rounded-sm',
                    isHighest ? 'bg-emerald-500' : isLowest ? 'bg-rose-500/70' : 'bg-muted-foreground/30'
                  )}
                  style={{ height: `${Math.max((pct / maxPct) * 100, 3)}%` }}
                />
              </div>
              <span className="text-[9px] text-muted-foreground">{digit}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function TickSparkline({ prices }: { prices: number[] }) {
  const points = prices.slice(-24);
  if (points.length < 2) {
    return (
      <div className="h-24 flex items-center justify-center text-xs text-muted-foreground">
        <Localize i18n_default_text="Waiting for enough ticks…" />
      </div>
    );
  }
  const min = Math.min(...points);
  const max = Math.max(...points);
  const range = max - min || 1;
  const w = 600;
  const h = 90;
  const coords = points.map((p, i) => {
    const x = (i / (points.length - 1)) * w;
    const y = h - ((p - min) / range) * (h - 16) - 8;
    return [x, y] as const;
  });
  const path = coords.map(([x, y], i) => `${i === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`).join(' ');
  return (
    <svg viewBox={`0 0 ${w} ${h}`} className="w-full h-24" preserveAspectRatio="none">
      <path d={path} fill="none" stroke="currentColor" className="text-primary" strokeWidth={2} />
      {coords.map(([x, y], i) => {
        const isLast = i === coords.length - 1;
        const isUp = i > 0 && points[i] >= points[i - 1];
        return (
          <circle
            key={i}
            cx={x}
            cy={y}
            r={isLast ? 4 : 2.5}
            className={isUp ? 'fill-emerald-500' : 'fill-rose-500'}
          />
        );
      })}
    </svg>
  );
}

export function TradeRobotView({
  isConnected,
  isAuthenticated,
  balanceLabel,
  symbols,
  activeSymbol,
  selectSymbol,
  currentTick,
  pipSize,
  tradeType,
  setTradeType,
  contractMode,
  setContractMode,
  selectedDigit,
  setSelectedDigit,
  stake,
  setStake,
  duration,
  setDuration,
  durationLimits,
  proposal,
  isProposalLoading,
  buyContract,
  isBuying,
  buyResult,
  buyError,
  clearBuyResult,
  openPositions,
  closedPositions,
  sellContract,
  sellingId,
  sellError,
  clearSellError,
}: TradeRobotViewProps) {
  const { localize } = useAppTranslations();
  const digitTradeTypeOptions = getDigitTradeTypeOptions(localize);
  const digitContractLabels = getDigitContractLabels(localize);

  const [activeTab, setActiveTab] = useState<Tab>('digits');
  const [priceHistory, setPriceHistory] = useState<number[]>([]);

  // Same digits as priceHistory, but paired with a stable per-tick id so the
  // "Most recent digits" strip can animate entries gliding in/along instead
  // of snapping — an index-based key would misidentify which square is
  // actually new as the window slides.
  const digitLogIdRef = useRef(0);
  const [digitLog, setDigitLog] = useState<{ id: number; digit: number }[]>([]);

  // Local, informational bot-settings state. There is no automated execution
  // engine wired up yet — starting the robot only shows a notice below.
  const [multiplier, setMultiplier] = useState('2.5');
  const [virtualLosses, setVirtualLosses] = useState('0');
  const [startWithVirtual, setStartWithVirtual] = useState(true);
  const [analyzeAmount, setAnalyzeAmount] = useState('100');
  const [reanalyzeAfter, setReanalyzeAfter] = useState('2');
  const [initialAmount, setInitialAmount] = useState('1');
  const [targetProfit, setTargetProfit] = useState('5');
  const [stopLossMultiplier, setStopLossMultiplier] = useState('6');

  // Reset the rolling tick buffer whenever the active market changes.
  useEffect(() => {
    setPriceHistory([]);
    setDigitLog([]);
  }, [activeSymbol?.underlying_symbol]);

  useEffect(() => {
    if (currentTick) {
      digitLogIdRef.current += 1;
      const id = digitLogIdRef.current;
      const digit = getLastDigit(currentTick.quote, pipSize);
      setDigitLog((prev) => {
        const next = [...prev, { id, digit }];
        return next.length > RECENT_DIGITS_SHOWN ? next.slice(-RECENT_DIGITS_SHOWN) : next;
      });
    }
  }, [currentTick, pipSize]);

  useEffect(() => {
    if (currentTick) {
      setPriceHistory((prev) => {
        const next = [...prev, currentTick.quote];
        return next.length > HISTORY_WINDOW ? next.slice(-HISTORY_WINDOW) : next;
      });
    }
  }, [currentTick]);

  const overallStats = useMemo(
    () => computeDigitStats(priceHistory, pipSize),
    [priceHistory, pipSize]
  );
  const last25 = useMemo(
    () => computeDigitStats(priceHistory.slice(-25), pipSize),
    [priceHistory, pipSize]
  );
  const last50 = useMemo(
    () => computeDigitStats(priceHistory.slice(-50), pipSize),
    [priceHistory, pipSize]
  );
  const last100 = useMemo(
    () => computeDigitStats(priceHistory.slice(-100), pipSize),
    [priceHistory, pipSize]
  );
  // The digit currently
