'use client';

import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { toast } from 'sonner';
import { Localize } from '@deriv-com/translations';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { SymbolSelector } from '@/components/custom/symbol-selector';
import { TradeControls, getContractModeOptions } from '@/components/trade-controls';
import { PositionsTable } from '@/components/custom/positions-table';
import { VictoryDialog } from '@/components/custom/victory-dialog';
import { DefeatDialog } from '@/components/custom/defeat-dialog';
import { cn } from '@/lib/utils';
import { useAppTranslations } from '@/components/custom/i18n-provider';
import { computeDigitStats, getLastDigit } from '@/lib/digit-stats';
import { useAutoBot, type BotPhase } from '@/hooks/use-auto-bot';
import { useRaBot, type RaPhase, type RaTradingMode } from '@/hooks/use-ra-bot';
import { useIsMobile } from '@/hooks/use-is-mobile';
import type {
  ActiveSymbol,
  Tick,
  DurationLimits,
  ProposalInfo,
  BuyResult,
} from '@deriv/core';
import type {
  ContractMode,
  TradeType,
  DigitStats,
  OpenPosition,
  ClosedPosition,
} from '@/lib/types';

const DIGIT_CONTRACT_TYPES = [
  'DIGITMATCH',
  'DIGITDIFF',
  'DIGITOVER',
  'DIGITUNDER',
  'DIGITEVEN',
  'DIGITODD',
];

function getDigitContractLabels(
  localize: (text: string) => string
): Record<string, string> {
  return {
    DIGITMATCH: localize('Digit Match'),
    DIGITDIFF: localize('Digit Differs'),
    DIGITOVER: localize('Digit Over'),
    DIGITUNDER: localize('Digit Under'),
    DIGITEVEN: localize('Digit Even'),
    DIGITODD: localize('Digit Odd'),
  };
}

function getDigitTradeTypeOptions(
  localize: (text: string) => string
): { value: TradeType; label: string }[] {
  return [
    { value: 'matches-differs', label: localize('Matches/Differs') },
    { value: 'over-under', label: localize('Over/Under') },
    { value: 'even-odd', label: localize('Even/Odd') },
  ];
}

type Tab = 'chart' | 'digits' | 'trades' | 'logs';

export interface TradeRobotViewProps {
  isConnected: boolean;
  isAuthenticated: boolean;
  balanceLabel: string | null;

  symbols: ActiveSymbol[];
  activeSymbol: ActiveSymbol | null;
  selectSymbol: (symbol: string) => void;
  currentTick: Tick | null;
  /** Full tick-price history (includes pre-fetched history, not just live ticks). */
  prices: number[];
  pipSize: number;

  tradeType: TradeType;
  setTradeType: (type: TradeType) => void;
  contractMode: ContractMode;
  setContractMode: (mode: ContractMode) => void;
  selectedDigit: number;
  setSelectedDigit: (digit: number) => void;
  stake: string;
  setStake: (value: string) => void;
  duration: number;
  setDuration: (value: number) => void;
  durationLimits: DurationLimits;
  proposal: ProposalInfo | null;
  isProposalLoading: boolean;
  buyContract: () => Promise<void>;
  isBuying: boolean;
  buyResult: BuyResult | null;
  buyError: string | null;
  clearBuyResult: () => void;

  openPositions: OpenPosition[];
  closedPositions: ClosedPosition[];
  sellContract: (contractId: number, bidPrice: string) => Promise<void>;
  sellingId: number | null;
  sellError: string | null;
  clearSellError: () => void;
}

const HISTORY_WINDOW = 100;
const RECENT_DIGITS_SHOWN = 26;
const ROBOT_SETTINGS_STORAGE_KEY = 'centurium:robot-settings';

interface SavedRobotSettings {
  multiplier: string;
  martingaleAfterLosses: string;
  initialAmount: string;
  targetProfit: string;
  stopLossLosses: string;
  duration: number;
}

// Same spring used for the equivalent glide animation on the standalone
// Digits page, so the motion feels identical across both pages.
const ROBOT_GLIDE_SPRING = { type: 'spring', stiffness: 340, damping: 30, mass: 0.7 } as const;

function DigitFrequencyRow({
  digitStats,
  selectedDigit,
  onSelect,
  lastDigit,
}: {
  digitStats: DigitStats;
  selectedDigit: number;
  onSelect: (digit: number) => void;
  /** The digit currently being generated by the live tick stream — when
   *  provided, a glowing pointer glides to whichever button this matches,
   *  matching the animation on the standalone Digits page. */
  lastDigit?: number | null;
}) {
  const maxPct = Math.max(...digitStats.percentages);
  const minPct = Math.min(...digitStats.percentages);
  return (
    <div className="grid grid-cols-5 sm:grid-cols-10 gap-2">
      {digitStats.percentages.map((pct, digit) => {
        const isSelected = digit === selectedDigit;
        const isCurrent = digit === lastDigit;
        const isHighest = digitStats.totalTicks > 0 && pct === maxPct;
        const isLowest = digitStats.totalTicks > 0 && pct === minPct;
        return (
          <button
            key={digit}
            onClick={() => onSelect(digit)}
            className={cn(
              'relative flex flex-col items-center gap-1 rounded-md border py-2 transition-all duration-200',
              isSelected
                ? 'border-destructive ring-1 ring-destructive'
                : isHighest
                  ? 'border-emerald-500/60'
                  : 'border-border',
              'bg-muted/30 hover:bg-muted/60 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]'
            )}
          >
            {isCurrent && (
              <>
                {/* Caret — glides above whichever digit is currently live */}
                <motion.span
                  layoutId="robot-digit-pointer-caret-live"
                  transition={ROBOT_GLIDE_SPRING}
                  className="pointer-events-none absolute -top-2.5 left-1/2 h-0 w-0 -translate-x-1/2 border-x-[5px] border-t-[6px] border-x-transparent border-t-primary"
                />
                {/* Glow ring — glides to sit around the currently live digit */}
                <motion.span
                  layoutId="robot-digit-pointer-glow-live"
                  transition={ROBOT_GLIDE_SPRING}
                  className="pointer-events-none absolute -inset-0.5 rounded-md ring-2 ring-primary shadow-[0_0_14px_2px] shadow-primary/50"
                />
              </>
            )}
            <span className="text-lg font-bold text-foreground">{digit}</span>
            <span
              className={cn(
                'text-xs font-mono font-bold',
                isHighest && 'text-emerald-400',
                isLowest && 'text-rose-400',
                !isHighest && !isLowest && 'text-foreground/80'
              )}
            >
              {pct.toFixed(1)}%
            </span>
          </button>
        );
      })}
    </div>
  );
}

function DigitHistogram({ title, stats }: { title: string; stats: DigitStats }) {
  const maxPct = Math.max(...stats.percentages, 1);
  const highest = Math.max(...stats.percentages);
  const lowest = Math.min(...stats.percentages);
  return (
    <div className="flex flex-col gap-2">
      <span className="text-xs font-semibold text-foreground/90">{title}</span>
      <div className="flex items-end gap-1 h-28">
        {stats.percentages.map((pct, digit) => {
          const isHighest = stats.totalTicks > 0 && pct === highest;
          const isLowest = stats.totalTicks > 0 && pct === lowest;
          return (
            <div
              key={digit}
              className="flex-1 flex flex-col items-center gap-1 rounded-md py-1 transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]"
            >
              <span
                className={cn(
                  'text-[10px] font-bold',
                  isHighest ? 'text-emerald-400' : isLowest ? 'text-rose-400' : 'text-foreground/80'
                )}
              >
                {stats.totalTicks > 0 ? `${Math.round(pct)}%` : ''}
              </span>
              <div className="w-full h-20 flex items-end">
                <div
                  className={cn(
                    'w-full rounded-sm',
                    isHighest ? 'bg-emerald-500' : isLowest ? 'bg-rose-500/70' : 'bg-muted-foreground/50'
                  )}
                  style={{ height: `${Math.max((pct / maxPct) * 100, 3)}%` }}
                />
              </div>
              <span className="text-[10px] font-semibold text-foreground/80">{digit}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function TickSparkline({ prices }: { prices: number[] }) {
  const points = prices.slice(-24);
  if (points.length < 2) {
    return (
      <div className="h-24 flex items-center justify-center text-xs font-semibold text-foreground/90">
        <Localize i18n_default_text="Waiting for enough ticks…" />
      </div>
    );
  }
  const min = Math.min(...points);
  const max = Math.max(...points);
  const range = max - min || 1;
  const w = 600;
  const h = 90;
  const coords = points.map((p, i) => {
    const x = (i / (points.length - 1)) * w;
    const y = h - ((p - min) / range) * (h - 16) - 8;
    return [x, y] as const;
  });
  const path = coords.map(([x, y], i) => `${i === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`).join(' ');
  return (
    <svg viewBox={`0 0 ${w} ${h}`} className="w-full h-24" preserveAspectRatio="none">
      <path d={path} fill="none" stroke="currentColor" className="text-primary" strokeWidth={2} />
      {coords.map(([x, y], i) => {
        const isLast = i === coords.length - 1;
        const isUp = i > 0 && points[i] >= points[i - 1];
        return (
          <circle
            key={i}
            cx={x}
            cy={y}
            r={isLast ? 4 : 2.5}
            className={isUp ? 'fill-emerald-500' : 'fill-rose-500'}
          />
        );
      })}
    </svg>
  );
}

function getBotStatusLabel(phase: BotPhase, localize: (t: string) => string): string {
  switch (phase) {
    case 'idle':
      return localize('Not running');
    case 'awaiting-proposal':
    case 'awaiting-buy':
      return localize('Placing trade…');
    case 'awaiting-settlement':
      return localize('Trade running…');
    case 'stopped-target':
      return localize('Stopped — target profit reached');
    case 'stopped-loss':
      return localize('Stopped — stop-loss reached');
    case 'stopped-error':
      return localize('Stopped — trade failed');
    default:
      return localize('Not running');
  }
}

function getRaStatusLabel(phase: RaPhase, localize: (t: string) => string): string {
  switch (phase) {
    case 'idle':
      return localize('Watching…');
    case 'awaiting-proposal':
    case 'awaiting-buy':
      return localize('Placing trade…');
    case 'awaiting-settlement':
      return localize('Trade running…');
    default:
      return localize('Watching…');
  }
}

function getRaStoppedLabel(
  reason: 'manual' | 'take-profit' | 'stop-loss' | null,
  localize: (t: string) => string
): string | null {
  switch (reason) {
    case 'manual':
      return localize('Stopped: Manual');
    case 'take-profit':
      return localize('Stopped: Take Profit');
    case 'stop-loss':
      return localize('Stopped: Stop Loss');
    default:
      return null;
  }
}

/** Small strip of the last digits seen while Ra was on — oldest to newest,
 *  over4 (5-9) and under5 (0-4) colored differently, newest highlighted.
 *  Native equivalent of the extension's popup "Digit Record". */
function RaDigitRecord({ digits }: { digits: number[] }) {
  if (digits.length === 0) return null;
  return (
    <div className="flex flex-wrap gap-1 rounded-md bg-muted/30 p-2">
      {digits.map((d, i) => {
        const isOver4 = d > 4;
        const isNewest = i === digits.length - 1;
        return (
          <span
            key={i}
            className={cn(
              'flex h-5 w-5 items-center justify-center rounded text-[10px] font-bold tabular-nums',
              isOver4 ? 'bg-emerald-500/25 text-emerald-400' : 'bg-rose-500/25 text-rose-400',
              isNewest && 'ring-2 ring-primary'
            )}
          >
            {d}
          </span>
        );
      })}
    </div>
  );
}

type RobotPanelKey = 'settings' | 'analysis' | 'manual';

/**
 * Same premium hover micro-interaction used on the homepage's entry cards:
 * the hovered panel lifts/scales up and its `.panel-glow` breathing glow
 * gets a brighter overlay faded in on top (rather than swapping the
 * keyframes, which would make the glow jump instead of smoothly
 * intensifying). The other panels dim slightly while one is hovered.
 */
function useRobotPanelHover() {
  const [hovered, setHovered] = useState<RobotPanelKey | null>(null);

  function panelProps(key: RobotPanelKey) {
    const isHovered = hovered === key;
    const isDimmed = hovered !== null && hovered !== key;
    return {
      onMouseEnter: () => setHovered(key),
      onMouseLeave: () =>
        setHovered((current: RobotPanelKey | null) => (current === key ? null : current)),
      onFocus: () => setHovered(key),
      onBlur: () =>
        setHovered((current: RobotPanelKey | null) => (current === key ? null : current)),
      style: {
        transform: isHovered ? 'translateY(-4px) scale(1.02)' : 'translateY(0) scale(1)',
        opacity: isDimmed ? 0.92 : 1,
      },
      className:
        'relative transition-[transform,opacity] duration-300 ease-out will-change-transform',
      overlayClassName:
        'pointer-events-none absolute inset-0 rounded-[inherit] transition-opacity duration-300 ease-out shadow-[0_14px_32px_-12px_rgba(0,0,0,0.35),0_0_0_1px_rgba(59,130,246,0.55),0_0_26px_4px_rgba(59,130,246,0.45),0_0_56px_14px_rgba(59,130,246,0.22)]' +
        (isHovered ? ' opacity-100' : ' opacity-0'),
    };
  }

  return panelProps;
}

/** Which side panel is currently open. The two are mutually exclusive —
 *  opening one always collapses the other, and the Digit panel in between
 *  is never collapsed, only pushed left/right by the resulting resize. */
type OpenSide = 'automated' | 'manual';

// Widths for the two side panels (desktop/lg only — on mobile both panels
// are always shown at full width, stacked, since there's no horizontal
// space to fight over there).
const AUTOMATED_OPEN_WIDTH = 420;
const MANUAL_OPEN_WIDTH = 300;
const SIDE_COLLAPSED_WIDTH = 40;

/**
 * A side panel (Automated Robot or Manual) that can collapse down to a
 * thin strip showing only a subtle arrow. This behaves like a real
 * sliding drawer: the panel's content stays mounted and fully visible at
 * all times — nothing fades or swaps — while the wrapper's *width*
 * animates continuously between its open and collapsed size. A
 * `clip-path` on the wrapper reveals/hides the content as that width
 * changes, so the whole thing reads as one continuous slide rather than
 * a pop-in/vanish.
 *
 * `clip-path` is used instead of `overflow-hidden` deliberately: unlike
 * `overflow`, it doesn't establish a new scroll/containing context, so it
 * won't interfere with the Automated panel's `position: sticky` scroll
 * behavior.
 *
 * All of the panel's actual data (form values, selections, etc.) lives in
 * state one level up in `TradeRobotView` — the Card here is a plain
 * presentation of that state — so keeping it mounted while collapsed
 * costs nothing and there's no state to lose.
 */
function CollapsibleSidePanel({
  isMobile,
  isOpen,
  onExpand,
  openWidth,
  arrowSide,
  arrowIcon: ArrowIcon,
  ariaLabel,
  children,
}: {
  isMobile: boolean;
  isOpen: boolean;
  onExpand: () => void;
  openWidth: number;
  /** Which edge of the wrapper the collapsed arrow sits on — this is
   *  always the panel's "inner" edge, the one that moves as it
   *  slides open/shut. */
  arrowSide: 'left' | 'right';
  arrowIcon: typeof ChevronLeft;
  ariaLabel: string;
  children: React.ReactNode;
}) {
  if (isMobile) {
    // No horizontal space constraint when stacked — always show in full.
    return <div className="w-full">{children}</div>;
  }

  return (
    <motion.div
      initial={false}
      animate={{ width: isOpen ? openWidth : SIDE_COLLAPSED_WIDTH }}
      transition={ROBOT_GLIDE_SPRING}
      style={{ clipPath: 'inset(0)' }}
      className="relative shrink-0 self-stretch"
    >
      {/* Fixed at its full open width so it never reflows — the wrapper's
          clip-path is what continuously reveals or hides it as the width
          above animates, which is what produces the sliding motion. */}
      <div
        style={{ width: openWidth }}
        className={cn('h-full', !isOpen && 'pointer-events-none')}
        aria-hidden={!isOpen}
      >
        {children}
      </div>

      {/* Collapsed-state arrow, anchored to the panel's inner edge (so it
          sits in the right spot whether the panel is open or shut) and
          simply cross-fading in as the slide finishes closing. Bold and
          purple with a breathing glow — deliberately eye-catching rather
          than subtle, so a first-time user notices there's a panel to
          expand instead of missing it as a sliver of dead space. */}
      <button
        type="button"
        onClick={onExpand}
        aria-label={ariaLabel}
        tabIndex={isOpen ? -1 : 0}
        className={cn(
          'side-panel-arrow absolute inset-y-0 flex items-center justify-center rounded-xl border-2 bg-card/95 backdrop-blur-sm text-purple-400 hover:text-purple-200 hover:bg-card transition-[opacity,color] duration-200',
          arrowSide === 'right' ? 'right-0' : 'left-0',
          isOpen ? 'opacity-0 pointer-events-none' : 'opacity-100'
        )}
        style={{ width: SIDE_COLLAPSED_WIDTH }}
      >
        <ArrowIcon className="h-5 w-5" strokeWidth={2.75} />
      </button>
    </motion.div>
  );
}

export function TradeRobotView({
  isConnected,
  isAuthenticated,
  balanceLabel,
  symbols,
  activeSymbol,
  selectSymbol,
  currentTick,
  prices,
  pipSize,
  tradeType,
  setTradeType,
  contractMode,
  setContractMode,
  selectedDigit,
  setSelectedDigit,
  stake,
  setStake,
  duration,
  setDuration,
  durationLimits,
  proposal,
  isProposalLoading,
  buyContract,
  isBuying,
  buyResult,
  buyError,
  clearBuyResult,
  openPositions,
  closedPositions,
  sellContract,
  sellingId,
  sellError,
  clearSellError,
}: TradeRobotViewProps) {
  const { localize } = useAppTranslations();
  const digitTradeTypeOptions = getDigitTradeTypeOptions(localize);
  const digitContractLabels = getDigitContractLabels(localize);
  const contractModeOptions = getContractModeOptions(localize)[tradeType];

  const getPanelProps = useRobotPanelHover();
  const settingsPanel = getPanelProps('settings');
  const analysisPanel = getPanelProps('analysis');
  const manualPanel = getPanelProps('manual');

  const isMobile = useIsMobile();
  // Automated Robot is expanded and Manual is collapsed by default; the two
  // are mutually exclusive, so a single value fully describes the layout.
  const [openSide, setOpenSide] = useState<OpenSide>('automated');
  const isAutomatedOpen = openSide === 'automated';
  const isManualOpen = openSide === 'manual';

  const [activeTab, setActiveTab] = useState<Tab>('digits');
  // `prices` already contains the pre-fetched history merged with live ticks
  // (see useTicks), so derive from it directly instead of keeping a separate
  // buffer that would start empty and duplicate/lag the real data.
  const priceHistory = useMemo(() => prices.slice(-HISTORY_WINDOW), [prices]);

  const [multiplier, setMultiplier] = useState('2.5');
  const [martingaleAfterLosses, setMartingaleAfterLosses] = useState('0');
  const [initialAmount, setInitialAmount] = useState('1');
  const [targetProfit, setTargetProfit] = useState('5');
  const [stopLossLosses, setStopLossLosses] = useState('4');

  // --- Ra mode: which automated strategy the left panel runs.
  const [botMode, setBotMode] = useState<'martingale' | 'ra'>('martingale');
  const [raStreakCount, setRaStreakCount] = useState('5');
  const [raConfirmationStreak, setRaConfirmationStreak] = useState('5');
  const [raTpIncrement, setRaTpIncrement] = useState('0');
  const [raCooldownSeconds, setRaCooldownSeconds] = useState('60');
  const [raTradingMode, setRaTradingMode] = useState<RaTradingMode>('neutral');
  const [raAccountTakeProfit, setRaAccountTakeProfit] = useState('0');
  const [raAccountStopLoss, setRaAccountStopLoss] = useState('0');

  // Load any saved robot settings once on mount.
  useEffect(() => {
    try {
      const raw = window.localStorage.getItem(ROBOT_SETTINGS_STORAGE_KEY);
      if (!raw) return;
      const saved = JSON.parse(raw) as Partial<SavedRobotSettings>;
      if (typeof saved.multiplier === 'string') setMultiplier(saved.multiplier);
      if (typeof saved.martingaleAfterLosses === 'string') setMartingaleAfterLosses(saved.martingaleAfterLosses);
      if (typeof saved.initialAmount === 'string') setInitialAmount(saved.initialAmount);
      if (typeof saved.targetProfit === 'string') setTargetProfit(saved.targetProfit);
      if (typeof saved.stopLossLosses === 'string') setStopLossLosses(saved.stopLossLosses);
      if (typeof saved.duration === 'number') setDuration(saved.duration);
    } catch {
      // Ignore malformed/unavailable storage — fields just keep their defaults.
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleSaveSettings = () => {
    try {
      const payload: SavedRobotSettings = {
        multiplier,
        martingaleAfterLosses,
        initialAmount,
        targetProfit,
        stopLossLosses,
        duration,
      };
      window.localStorage.setItem(ROBOT_SETTINGS_STORAGE_KEY, JSON.stringify(payload));
      toast.success(localize('Settings saved'));
    } catch {
      toast.error(localize('Could not save settings on this device.'));
    }
  };

  const overallStats = useMemo(
    () => computeDigitStats(priceHistory, pipSize),
    [priceHistory, pipSize]
  );
  const last25 = useMemo(
    () => computeDigitStats(priceHistory.slice(-25), pipSize),
    [priceHistory, pipSize]
  );
  const last50 = useMemo(
    () => computeDigitStats(priceHistory.slice(-50), pipSize),
    [priceHistory, pipSize]
  );
  const last100 = useMemo(
    () => computeDigitStats(priceHistory.slice(-100), pipSize),
    [priceHistory, pipSize]
  );
  const recentDigits = useMemo(
    () => priceHistory.slice(-RECENT_DIGITS_SHOWN).map((p) => getLastDigit(p, pipSize)),
    [priceHistory, pipSize]
  );
  const lastDigit = useMemo(
    () => (currentTick ? getLastDigit(currentTick.quote, pipSize) : null),
    [currentTick, pipSize]
  );

  const bot = useAutoBot({
    pipSize,
    setStake,
    proposal,
    isProposalLoading,
    buyContract,
    buyResult,
    buyError,
    clearBuyResult,
    openPositions,
  });

  const raBot = useRaBot({
    currentTick,
    pipSize,
    setContractMode,
    setSelectedDigit,
    proposal,
    isProposalLoading,
    buyContract,
    buyResult,
    buyError,
    clearBuyResult,
    openPositions,
  });

  // Whichever strategy is currently selected — used to gate Manual mode and
  // to decide what the Start/Stop button and header status line show.
  const activeBotRunning = botMode === 'ra' ? raBot.running : bot.running;

  // Celebration modal — opens the moment the bot's phase flips to
  // `stopped-target`, independent of that phase so the user can dismiss it
  // (and start a new run) without the phase itself changing.
  const [victoryOpen, setVictoryOpen] = useState(false);
  useEffect(() => {
    if (bot.phase === 'stopped-target') {
      setVictoryOpen(true);
    }
  }, [bot.phase]);

  // Same pattern as the victory modal above, but for the stop-loss phase.
  const [defeatOpen, setDefeatOpen] = useState(false);
  useEffect(() => {
    if (bot.phase === 'stopped-loss') {
      setDefeatOpen(true);
    }
  }, [bot.phase]);

  const handleRaStart = () => {
    if (raBot.running) {
      raBot.stop('manual');
      toast.info(localize('Robot stopped'));
      return;
    }
    const streakCount = parseInt(raStreakCount, 10);
    const confirmationStreak = parseInt(raConfirmationStreak, 10);
    if (!streakCount || streakCount < 2 || streakCount > 20) {
      toast.error(localize('Enter a valid Streak Count (2-20) first.'));
      return;
    }
    if (!confirmationStreak || confirmationStreak < 2 || confirmationStreak > 20) {
      toast.error(localize('Enter a valid Confirmation Streak (2-20) first.'));
      return;
    }
    raBot.start({
      streakCount,
      confirmationStreak,
      tpIncrement: parseFloat(raTpIncrement) || 0,
      cooldownSeconds: Math.max(0, parseInt(raCooldownSeconds, 10) || 0),
      tradingMode: raTradingMode,
      accountTakeProfit: parseFloat(raAccountTakeProfit) || 0,
      accountStopLoss: parseFloat(raAccountStopLoss) || 0,
    });
    toast.info(localize('Robot started'), {
      description:
        raTradingMode === 'neutral'
          ? localize('Watching for arm/confirm streaks — pick Trend or Counter to actually trade.')
          : localize('Watching for arm/confirm streaks on the digit stream.'),
    });
  };

  const handleStart = () => {
    if (botMode === 'ra') {
      handleRaStart();
      return;
    }
    if (bot.running) {
      bot.stop();
      toast.info(localize('Robot stopped'));
      return;
    }
    const initial = parseFloat(initialAmount);
    if (!initial || initial <= 0) {
      toast.error(localize('Enter a valid initial stake first.'));
      return;
    }
    const mult = parseFloat(multiplier) || 1;
    const martingaleStartAfter = Math.max(0, parseInt(martingaleAfterLosses, 10) || 0);
    const target = parseFloat(targetProfit);
    const lossCount = parseInt(stopLossLosses, 10);
    if (!lossCount || lossCount <= 0) {
      toast.error(localize('Enter a valid number of losses first.'));
      return;
    }
    bot.start({
      initialStake: initial,
      multiplier: mult,
      martingaleStartAfter,
      targetProfit: target > 0 ? target : Infinity,
      stopLossLossCount: lossCount,
      stopLossAmount: Infinity,
    });
    toast.info(localize('Robot started'), {
      description:
        martingaleStartAfter > 0
          ? localize('Trading at the initial stake until a loss streak triggers the martingale.')
          : localize('Placing trades using the settings on the left.'),
    });
  };

  return (
    <>
    <VictoryDialog
      open={victoryOpen}
      onOpenChange={setVictoryOpen}
      onContinue={() => setVictoryOpen(false)}
    />
    <DefeatDialog
      open={defeatOpen}
      onOpenChange={setDefeatOpen}
      onContinue={() => setDefeatOpen(false)}
    />
    <div className="w-full max-w-[1760px] mx-auto px-3 py-4 sm:px-4 flex flex-col lg:flex-row gap-4">
      {/* Left: Automated Robot settings. Collapsible — expanded by default,
          and mutually exclusive with the Manual panel on the far right.
          Sticky with its own scroll area on desktop so it can be scrolled
          independently of the page. */}
      <CollapsibleSidePanel
        isMobile={isMobile}
        isOpen={isAutomatedOpen}
        onExpand={() => setOpenSide('automated')}
        openWidth={AUTOMATED_OPEN_WIDTH}
        arrowSide="right"
        arrowIcon={ChevronRight}
        ariaLabel={localize('Expand automated robot panel')}
      >
      <Card
        className={`panel-glow bg-card/60 backdrop-blur-md flex flex-col lg:sticky lg:top-[88px] lg:max-h-[calc(100dvh-124px)] overflow-visible ${settingsPanel.className}`}
        style={settingsPanel.style}
        onMouseEnter={settingsPanel.onMouseEnter}
        onMouseLeave={settingsPanel.onMouseLeave}
        onFocus={settingsPanel.onFocus}
        onBlur={settingsPanel.onBlur}
      >
        <div aria-hidden className={settingsPanel.overlayClassName} />
        <CardHeader className="pb-3 shrink-0 lg:rounded-t-[inherit]">
          <CardTitle className="text-base">
            <Localize i18n_default_text="Robot settings" />
          </CardTitle>
          <p className="text-xs font-semibold text-foreground/90">
            {isConnected ? (
              balanceLabel ? (
                balanceLabel
              ) : (
                <Localize i18n_default_text="Connected" />
              )
            ) : (
              <Localize i18n_default_text="Not connected" />
            )}
          </p>
          <div className="flex items-center justify-between rounded-md bg-muted/40 px-2.5 py-1.5 mt-1">
            <span className={cn('text-xs font-bold', activeBotRunning ? 'text-emerald-400' : 'text-foreground/85')}>
              {botMode === 'ra' ? getRaStatusLabel(raBot.phase, localize) : getBotStatusLabel(bot.phase, localize)}
            </span>
            <div className="flex items-center gap-1.5">
              <span
                className={cn(
                  'text-sm font-mono font-bold tabular-nums',
                  (botMode === 'ra' ? raBot.pnl : bot.pnl) >= 0 ? 'text-emerald-400' : 'text-rose-400'
                )}
              >
                {(botMode === 'ra' ? raBot.pnl : bot.pnl) >= 0 ? '+' : ''}
                {(botMode === 'ra' ? raBot.pnl : bot.pnl).toFixed(2)}
              </span>
              {botMode === 'martingale' && (
                <button
                  type="button"
                  onClick={bot.resetPnl}
                  title={localize('Reset profit/loss to 0')}
                  className="text-[10px] uppercase tracking-wide text-muted-foreground hover:text-foreground border border-border rounded px-1.5 py-0.5 transition-colors"
                >
                  <Localize i18n_default_text="Reset" />
                </button>
              )}
            </div>
          </div>
          {botMode === 'ra' && !raBot.running && getRaStoppedLabel(raBot.stoppedReason, localize) && (
            <p className="text-[11px] text-muted-foreground px-0.5">
              {getRaStoppedLabel(raBot.stoppedReason, localize)}
            </p>
          )}
        </CardHeader>
        <CardContent className="space-y-3 lg:flex-1 lg:min-h-0 lg:overflow-y-auto lg:rounded-b-[inherit]">
          <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5">
            <Label className="text-xs font-semibold text-foreground/90">
              <Localize i18n_default_text="Bot Mode" />
            </Label>
            <ToggleGroup
              type="single"
              value={botMode}
              onValueChange={(v) => {
                if (v && !activeBotRunning) setBotMode(v as 'martingale' | 'ra');
              }}
              className="w-full gap-0 rounded-full bg-muted p-1"
            >
              <ToggleGroupItem
                value="martingale"
                disabled={activeBotRunning}
                className="flex-1 rounded-full text-xs font-semibold text-foreground/70 data-[state=on]:bg-background data-[state=on]:text-primary data-[state=on]:font-bold data-[state=on]:shadow-sm hover:text-foreground"
              >
                <Localize i18n_default_text="Martingale" />
              </ToggleGroupItem>
              <ToggleGroupItem
                value="ra"
                disabled={activeBotRunning}
                className="flex-1 rounded-full text-xs font-semibold text-foreground/70 data-[state=on]:bg-background data-[state=on]:text-primary data-[state=on]:font-bold data-[state=on]:shadow-sm hover:text-foreground"
              >
                <Localize i18n_default_text="Ra" />
              </ToggleGroupItem>
            </ToggleGroup>
          </div>

          <fieldset disabled={activeBotRunning} className="space-y-3 border-0 p-0 m-0 min-w-0">
          <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5 transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]">
            <Label className="text-xs font-semibold text-foreground/90">
              <Localize i18n_default_text="Market" />
            </Label>
            <SymbolSelector
              symbols={symbols}
              activeSymbol={activeSymbol}
              onSymbolChange={selectSymbol}
            />
          </div>

          {botMode === 'martingale' && (
          <>
          <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5 transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]">
            <Label className="text-xs font-semibold text-foreground/90">
              <Localize i18n_default_text="Trade Type" />
            </Label>
            <Select value={tradeType} onValueChange={(v) => setTradeType(v as TradeType)}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {digitTradeTypeOptions.map((opt) => (
                  <SelectItem key={opt.value} value={opt.value}>
                    {opt.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5 transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]">
            <Label className="text-xs font-semibold text-foreground/90">
              <Localize i18n_default_text="Trade Function" />
            </Label>
            <ToggleGroup
              type="single"
              value={contractMode}
              onValueChange={(value) => {
                if (value) setContractMode(value as ContractMode);
              }}
              className="w-full gap-0 rounded-full bg-muted p-1"
            >
              {contractModeOptions.map((opt) => (
                <ToggleGroupItem
                  key={opt.value}
                  value={opt.value}
                  className="flex-1 rounded-full text-xs font-semibold text-foreground/70 data-[state=on]:bg-background data-[state=on]:text-primary data-[state=on]:font-bold data-[state=on]:shadow-sm hover:text-foreground"
                >
                  {opt.label}
                </ToggleGroupItem>
              ))}
            </ToggleGroup>
          </div>

          {tradeType !== 'even-odd' && (
            <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5 transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]">
              <Label className="text-xs font-semibold text-foreground/90">
                <Localize i18n_default_text="Prediction" />
              </Label>
              <Select
                value={String(selectedDigit)}
                onValueChange={(v) => setSelectedDigit(parseInt(v, 10))}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {Array.from({ length: 10 }, (_, d) => (
                    <SelectItem key={d} value={String(d)}>
                      {d}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}

          <div className="grid grid-cols-2 gap-2">
            <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5 transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]">
              <Label className="text-xs font-semibold text-foreground/90">
                <Localize i18n_default_text="Duration" />
              </Label>
              <Input
                type="number"
                value={duration}
                onChange={(e) => {
                  const val = parseInt(e.target.value, 10);
                  if (!isNaN(val)) setDuration(val);
                }}
                min={durationLimits.min}
                max={durationLimits.max}
                labelRight={localize('Ticks')}
              />
            </div>
            <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5 transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]">
              <Label className="text-xs font-semibold text-foreground/90">
                <Localize i18n_default_text="Multiplier" />
              </Label>
              <Input value={multiplier} onChange={(e) => setMultiplier(e.target.value)} />
            </div>
          </div>

          <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5 transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]">
            <Label
              className="text-xs font-semibold text-foreground/90"
              title={localize(
                'Stays at the initial stake for this many losses before the multiplier kicks in. 0 = multiply from the first loss.'
              )}
            >
              <Localize i18n_default_text="Martingale after N losses" />
            </Label>
            <Input
              value={martingaleAfterLosses}
              onChange={(e) => setMartingaleAfterLosses(e.target.value)}
            />
          </div>

          <div className="border-t border-border pt-2 grid grid-cols-3 gap-2">
            <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5 transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]">
              <Label className="text-xs font-semibold text-foreground/90">
                <Localize i18n_default_text="Initial" />
              </Label>
              <Input value={initialAmount} onChange={(e) => setInitialAmount(e.target.value)} />
            </div>
            <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5 transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]">
              <Label className="text-xs font-semibold text-foreground/90">
                <Localize i18n_default_text="Target profit" />
              </Label>
              <Input value={targetProfit} onChange={(e) => setTargetProfit(e.target.value)} />
            </div>
            <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5 transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]">
              <Label
                className="text-xs font-semibold text-foreground/90"
                title={localize('Stop after this many losses in a row')}
              >
                <Localize i18n_default_text="Stop loss" />
              </Label>
              <Input
                type="number"
                min={1}
                value={stopLossLosses}
                onChange={(e) => setStopLossLosses(e.target.value)}
                labelRight={localize('losses')}
              />
            </div>
          </div>
          </>
          )}

          {botMode === 'ra' && (
          <>
          <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5">
            <Label className="text-xs font-semibold text-foreground/90">
              <Localize i18n_default_text="Duration" />
            </Label>
            <Input
              type="number"
              value={duration}
              onChange={(e) => {
                const val = parseInt(e.target.value, 10);
                if (!isNaN(val)) setDuration(val);
              }}
              min={durationLimits.min}
              max={durationLimits.max}
              labelRight={localize('Ticks')}
            />
          </div>

          <div className="grid grid-cols-2 gap-2">
            <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5">
              <Label
                className="text-xs font-semibold text-foreground/90"
                title={localize('N consecutive same-side digits (over4 / under5) required to arm a run before confirmation starts.')}
              >
                <Localize i18n_default_text="Streak Count" />
              </Label>
              <Input
                type="number"
                min={2}
                max={20}
                value={raStreakCount}
                onChange={(e) => setRaStreakCount(e.target.value)}
              />
            </div>
            <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5">
              <Label
                className="text-xs font-semibold text-foreground/90"
                title={localize('M more consecutive same-side digits, uninterrupted, required after arming before the trade fires.')}
              >
                <Localize i18n_default_text="Confirmation Streak" />
              </Label>
              <Input
                type="number"
                min={2}
                max={20}
                value={raConfirmationStreak}
                onChange={(e) => setRaConfirmationStreak(e.target.value)}
              />
            </div>
          </div>

          <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5">
            <Label className="text-xs font-semibold text-foreground/90">
              <Localize i18n_default_text="Trading Mode" />
            </Label>
            <ToggleGroup
              type="single"
              value={raTradingMode}
              onValueChange={(v) => {
                if (v) setRaTradingMode(v as RaTradingMode);
              }}
              className="w-full gap-0 rounded-full bg-muted p-1"
            >
              <ToggleGroupItem value="trend" className="flex-1 rounded-full text-xs font-semibold text-foreground/70 data-[state=on]:bg-background data-[state=on]:text-primary data-[state=on]:font-bold data-[state=on]:shadow-sm hover:text-foreground">
                <Localize i18n_default_text="Trend" />
              </ToggleGroupItem>
              <ToggleGroupItem value="neutral" className="flex-1 rounded-full text-xs font-semibold text-foreground/70 data-[state=on]:bg-background data-[state=on]:text-primary data-[state=on]:font-bold data-[state=on]:shadow-sm hover:text-foreground">
                <Localize i18n_default_text="Neutral" />
              </ToggleGroupItem>
              <ToggleGroupItem value="counter" className="flex-1 rounded-full text-xs font-semibold text-foreground/70 data-[state=on]:bg-background data-[state=on]:text-primary data-[state=on]:font-bold data-[state=on]:shadow-sm hover:text-foreground">
                <Localize i18n_default_text="Counter" />
              </ToggleGroupItem>
            </ToggleGroup>
            <p className="text-[11px] text-muted-foreground">
              {raTradingMode === 'trend' && (
                <Localize i18n_default_text="Confirmed over4 → Superior 3, confirmed under5 → Inferior 6." />
              )}
              {raTradingMode === 'neutral' && (
                <Localize i18n_default_text="Won't trade until you pick Trend or Counter." />
              )}
              {raTradingMode === 'counter' && (
                <Localize i18n_default_text="Confirmed over4 → Inferior 6, confirmed under5 → Superior 3." />
              )}
            </p>
          </div>

          <div className="grid grid-cols-2 gap-2">
            <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5">
              <Label
                className="text-xs font-semibold text-foreground/90"
                title={localize('Added to the Account Take Profit threshold after every Ra win.')}
              >
                <Localize i18n_default_text="TP Increment" />
              </Label>
              <Input value={raTpIncrement} onChange={(e) => setRaTpIncrement(e.target.value)} labelRight="USD" />
            </div>
            <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5">
              <Label className="text-xs font-semibold text-foreground/90">
                <Localize i18n_default_text="Cooldown" />
              </Label>
              <Input
                type="number"
                min={0}
                value={raCooldownSeconds}
                onChange={(e) => setRaCooldownSeconds(e.target.value)}
                labelRight={localize('sec')}
              />
            </div>
          </div>

          <div className="border-t border-border pt-2 grid grid-cols-2 gap-2">
            <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5">
              <Label className="text-xs font-semibold text-foreground/90">
                <Localize i18n_default_text="Account Take Profit" />
              </Label>
              <Input
                value={raAccountTakeProfit}
                onChange={(e) => setRaAccountTakeProfit(e.target.value)}
                labelRight="USD"
              />
            </div>
            <div className="space-y-1.5 rounded-lg p-1.5 -m-1.5">
              <Label className="text-xs font-semibold text-foreground/90">
                <Localize i18n_default_text="Account Stop Loss" />
              </Label>
              <Input
                value={raAccountStopLoss}
                onChange={(e) => setRaAccountStopLoss(e.target.value)}
                labelRight="USD"
              />
            </div>
          </div>

          {(raBot.running || raBot.digitRecord.length > 0) && (
            <div className="space-y-1.5">
              <div className="flex items-center justify-between">
                <Label className="text-xs font-semibold text-foreground/90">
                  <Localize i18n_default_text="Digit Record" />
                </Label>
                {raBot.armedSide && (
                  <span className="text-[11px] font-semibold text-foreground/80">
                    {raBot.armedSide} · {raBot.confirmProgress}/{raConfirmationStreak}
                  </span>
                )}
              </div>
              <RaDigitRecord digits={raBot.digitRecord} />
            </div>
          )}
          </>
          )}
          </fieldset>

          {botMode === 'martingale' && (
            <Button
              className="w-full"
              variant="outline"
              onClick={handleSaveSettings}
            >
              <Localize i18n_default_text="Save settings" />
            </Button>
          )}

          <Button
            className="w-full"
            size="lg"
            variant={activeBotRunning ? 'destructive' : 'default'}
            onClick={handleStart}
            disabled={!isConnected || !isAuthenticated}
          >
            {activeBotRunning ? <Localize i18n_default_text="Stop" /> : <Localize i18n_default_text="Start" />}
          </Button>
          <p className="text-[11px] text-muted-foreground text-center">
            {isAuthenticated ? (
              <Localize i18n_default_text="Uses the same trading connection as Manual mode — only one can trade at a time." />
            ) : (
              <Localize i18n_default_text="Log in to run the robot." />
            )}
          </p>
        </CardContent>
      </Card>
      </CollapsibleSidePanel>

      {/* Center: Digit panel. Always visible, never collapses — it simply
          fills whichever space the two side panels leave it. Since the
          side panels animate their own width every frame (not via a
          discrete swap), the browser reflows this panel's size in lock
          step automatically — no extra animation needed here for it to
          read as being smoothly pushed left/right. */}
      <div className={isMobile ? 'w-full' : 'flex-1 min-w-0'}>
      <Card
        className={`panel-glow bg-card/60 backdrop-blur-md h-fit ${analysisPanel.className}`}
        style={analysisPanel.style}
        onMouseEnter={analysisPanel.onMouseEnter}
        onMouseLeave={analysisPanel.onMouseLeave}
        onFocus={analysisPanel.onFocus}
        onBlur={analysisPanel.onBlur}
      >
        <div aria-hidden className={analysisPanel.overlayClassName} />
        <CardHeader className="pb-0">
          <div className="flex items-center gap-5 border-b border-border">
            {(
              [
                ['chart', localize('Chart')],
                ['digits', localize('Digits')],
                ['trades', localize('Trades')],
                ['logs', localize('Logs')],
              ] as [Tab, string][]
            ).map(([key, label]) => (
              <button
                key={key}
                onClick={() => setActiveTab(key)}
                className={cn(
                  'pb-2.5 text-sm font-bold border-b-2 -mb-px transition-colors',
                  activeTab === key
                    ? 'border-primary text-foreground'
                    : 'border-transparent text-foreground/70 hover:text-foreground'
                )}
              >
                {label}
              </button>
            ))}
          </div>
        </CardHeader>
        <CardContent className="pt-4 space-y-6">
          {activeTab === 'digits' && (
            <>
              <div className="space-y-2">
                <p className="text-center text-sm font-medium">
                  <Localize i18n_default_text="Digits frequency percentage" />
                </p>
                <DigitFrequencyRow
                  digitStats={overallStats}
                  selectedDigit={selectedDigit}
                  onSelect={setSelectedDigit}
                  lastDigit={lastDigit}
                />
              </div>

              <div className="space-y-2">
                <p className="text-sm font-medium">
                  <Localize i18n_default_text="Most recent digits" />
                </p>
                <div className="flex flex-wrap gap-1.5">
                  {recentDigits.length === 0 && (
                    <span className="text-xs font-semibold text-foreground/90">
                      <Localize i18n_default_text="Waiting for ticks…" />
                    </span>
                  )}
                  {recentDigits.map((d, i) => {
                    const isLast = i === recentDigits.length - 1;
                    return (
                      <span
                        key={i}
                        className={cn(
                          'w-7 h-7 flex items-center justify-center rounded-md text-sm font-bold transition-shadow duration-200 hover:ring-1 hover:ring-yellow-400/70 hover:shadow-[0_0_14px_3px_rgba(250,204,21,0.45)]',
                          isLast
                            ? 'bg-primary text-primary-foreground'
                            : 'bg-muted text-foreground/85'
                        )}
                      >
                        {d}
                      </span>
                    );
                  })}
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <DigitHistogram title={localize('Last 25 digits')} stats={last25} />
                <DigitHistogram title={localize('Last 50 digits')} stats={last50} />
                <DigitHistogram title={localize('Last 100 digits')} stats={last100} />
              </div>

              <div className="space-y-2">
                <p className="text-sm font-medium">
                  <Localize i18n_default_text="Recent ticks" />
                </p>
                <TickSparkline prices={priceHistory} />
              </div>
            </>
          )}

          {activeTab === 'chart' && (
            <div className="py-10 text-center text-sm text-muted-foreground">
              <Localize i18n_default_text="A full price chart isn't wired into this view yet — the live spot and recent ticks are shown on the Digits tab." />
            </div>
          )}

          {activeTab === 'trades' && (
            <>
              {isAuthenticated ? (
                <PositionsTable
                  openPositions={openPositions.filter((p) => DIGIT_CONTRACT_TYPES.includes(p.contract_type))}
                  closedPositions={closedPositions.filter((p) => DIGIT_CONTRACT_TYPES.includes(p.contract_type))}
                  onSell={sellContract}
                  sellingId={sellingId}
                  sellError={sellError}
                  onClearSellError={clearSellError}
                  contractTypeLabels={digitContractLabels}
                  className="mt-0"
                />
              ) : (
                <div className="py-10 text-center text-sm text-muted-foreground">
                  <Localize i18n_default_text="Log in to see your open and closed positions." />
                </div>
              )}
            </>
          )}

          {activeTab === 'logs' && (
            <div className="space-y-1.5 max-h-[420px] overflow-y-auto">
              {bot.log.length === 0 && (
                <div className="py-10 text-center text-sm text-muted-foreground">
                  <Localize i18n_default_text="No robot activity yet — start it from the left panel." />
                </div>
              )}
              {[...bot.log].reverse().map((entry) => (
                <div
                  key={entry.id}
                  className="flex items-center justify-between text-xs rounded-md border border-border px-3 py-2"
                >
                  <div className="flex items-center gap-2">
                    <span className="px-1.5 py-0.5 rounded text-[10px] font-semibold uppercase bg-primary/10 text-primary">
                      {localize('Real')}
                    </span>
                    <span className="text-foreground/80 font-medium">
                      {new Date(entry.time).toLocaleTimeString()}
                    </span>
                    {entry.exitSpot !== null && (
                      <span className="tabular-nums font-mono font-semibold text-foreground">{entry.exitSpot.toFixed(pipSize)}</span>
                    )}
                  </div>
                  <div className="flex items-center gap-3">
                    <span className={entry.won ? 'text-emerald-400 font-bold' : 'text-rose-400 font-bold'}>
                      {entry.won ? localize('Win') : localize('Loss')}
                    </span>
                    <span className={cn('tabular-nums font-bold', entry.profit >= 0 ? 'text-emerald-400' : 'text-rose-400')}>
                      {entry.profit >= 0 ? '+' : ''}
                      {entry.profit.toFixed(2)}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
      </div>

      {/* Right: Manual mode. Collapsible — collapsed by default, and
          mutually exclusive with the Automated Robot panel on the far
          left. Opening it collapses Automated and pushes Digit left. */}
      <CollapsibleSidePanel
        isMobile={isMobile}
        isOpen={isManualOpen}
        onExpand={() => setOpenSide('manual')}
        openWidth={MANUAL_OPEN_WIDTH}
        arrowSide="left"
        arrowIcon={ChevronLeft}
        ariaLabel={localize('Expand manual mode panel')}
      >
      <Card
        className={`panel-glow bg-card/60 backdrop-blur-md h-fit ${manualPanel.className}`}
        style={manualPanel.style}
        onMouseEnter={manualPanel.onMouseEnter}
        onMouseLeave={manualPanel.onMouseLeave}
        onFocus={manualPanel.onFocus}
        onBlur={manualPanel.onBlur}
      >
        <div aria-hidden className={manualPanel.overlayClassName} />
        <CardHeader className="pb-3">
          <CardTitle className="text-base">
            <Localize i18n_default_text="Manual mode" />
          </CardTitle>
          <p className="text-xs font-semibold text-foreground/90">
            {activeSymbol?.underlying_symbol_name ?? localize('Select a market')}
          </p>
        </CardHeader>
        <CardContent>
          {activeBotRunning && (
            <p className="text-xs text-amber-500 bg-amber-500/10 rounded-md px-2.5 py-1.5 mb-3">
              <Localize i18n_default_text="Manual trading is paused while the robot is running." />
            </p>
          )}
          <fieldset disabled={activeBotRunning} className="border-0 p-0 m-0 min-w-0">
            <TradeControls
              tradeType={tradeType}
              contractMode={contractMode}
              onContractModeChange={setContractMode}
              selectedDigit={selectedDigit}
              isConnected={isConnected}
              stake={stake}
              onStakeChange={setStake}
              duration={duration}
              onDurationChange={setDuration}
              durationLimits={durationLimits}
              proposal={proposal}
              isProposalLoading={isProposalLoading}
              onBuy={buyContract}
              isBuying={isBuying}
              buyResult={buyResult}
              buyError={buyError}
              onClearBuyResult={clearBuyResult}
              isAuthenticated={isAuthenticated}
            />
          </fieldset>
        </CardContent>
      </Card>
      </CollapsibleSidePanel>
    </div>
    </>
  );
}
